// Adds/updates hand-drawn ASCII-art templates in tool/templates.json.
//
// Usage: dart run tool/add_templates.dart && dart run tool/split_templates.dart
// Each template: name, category, palette (char -> 0xAARRGGBB), rows ('.' = transparent).
// Templates with an existing name are replaced.
import 'dart:convert';
import 'dart:io';

class Art {
  const Art(this.name, this.category, this.palette, this.rows);
  final String name;
  final String category;
  final Map<String, int> palette;
  final List<String> rows;
}

const arts = <Art>[
  Art('Shaded Heart', 'Patterns', {
    'K': 0xFF3B0A1A, 'R': 0xFFE63946, 'L': 0xFFFF8FA3, 'D': 0xFFA4161A,
  }, [
    '................',
    '...KKKK..KKKK...',
    '..KRRRRKKRRRRK..',
    '.KRLLRRRRRRRRRK.',
    '.KRLRRRRRRRRRDK.',
    '.KRRRRRRRRRRRDK.',
    '.KRRRRRRRRRRDDK.',
    '..KRRRRRRRRRDK..',
    '..KRRRRRRRRDDK..',
    '...KRRRRRRDDK...',
    '....KRRRRDDK....',
    '.....KRRDDK.....',
    '......KDDK......',
    '.......KK.......',
    '................',
    '................',
  ]),
  Art('Skull', 'Objects', {
    'K': 0xFF2B2B2B, 'W': 0xFFF2F2F2, 'G': 0xFFC4C4C4,
  }, [
    '................',
    '....KKKKKKKK....',
    '..KKWWWWWWWWKK..',
    '.KWWWWWWWWWWWWK.',
    '.KWWWWWWWWWWWGK.',
    '.KWWKKKWWKKKWGK.',
    '.KWKKKKWWKKKKGK.',
    '.KWKKKKWWKKKKGK.',
    '.KWWKKWWWWKKWGK.',
    '..KWWWWKKWWWWK..',
    '..KGWWWWWWWWGK..',
    '...KWWKWWKWWK...',
    '...KWWKWWKWWK...',
    '....KKKKKKKK....',
    '................',
    '................',
  ]),
  Art('Crown', 'Objects', {
    'K': 0xFF5A3A00, 'Y': 0xFFFFD23F, 'L': 0xFFFFF0A0, 'O': 0xFFE09F1F,
    'R': 0xFFE63946, 'B': 0xFF3A86FF,
  }, [
    '................',
    '..K....KK....K..',
    '.KYK..KYYK..KYK.',
    '.KYYK.KYYK.KYYK.',
    '.KYLYKKYYKKYLYK.',
    '.KYLYYYYYYYYYYK.',
    '.KYYYYYYYYYYYOK.',
    '.KYYYYYYYYYYYOK.',
    '.KYYYRYYBYYRYOK.',
    '.KOOOOOOOOOOOOK.',
    '.KKKKKKKKKKKKKK.',
    '................',
  ]),
  Art('Shield', 'Objects', {
    'K': 0xFF1B263B, 'B': 0xFF3A86FF, 'D': 0xFF1D4E9E, 'L': 0xFF8FC1FF,
    'Y': 0xFFFFD23F, 'S': 0xFFC0C6D0,
  }, [
    '................',
    '..KKKKKKKKKKKK..',
    '.KSSSSSSSSSSSSK.',
    '.KSBBBBBBBBBBSK.',
    '.KSBLLBBBBBBDSK.',
    '.KSBLBBBYYBBDSK.',
    '.KSBBBYYYYBBDSK.',
    '.KSBBBBBYYBBDSK.',
    '.KSBBBBBYYBBDSK.',
    '..KSBBBBYYBDSK..',
    '..KSBBBBBBBDSK..',
    '...KSBBBBBDSK...',
    '....KSBBBDSK....',
    '.....KSBDSK.....',
    '......KKKK......',
    '................',
  ]),
  Art('Pumpkin', 'Nature', {
    'K': 0xFF3B1F0B, 'O': 0xFFF77F00, 'L': 0xFFFFA94D, 'D': 0xFFC45A00,
    'G': 0xFF2D6A4F,
  }, [
    '.......GG.......',
    '......KGGK......',
    '...KKKKGGKKKK...',
    '.KOOLLOOOOOOOOK.',
    'KOOLOOOOOODOOODK',
    'KOLOOOOOOOOOODDK',
    'KOOOKKOOOOKKOODK',
    'KOOKKKKOOKKKKODK',
    'KOOOOOOOKOOOOODK',
    'KOOKOOOOOOOOKODK',
    'KOOKKOOKKOOKKODK',
    'KDOOKKKKKKKKOODK',
    '.KDOOOOOOOOOODK.',
    '..KDDDDDDDDDDK..',
    '...KKKKKKKKKK...',
    '................',
  ]),
  Art('Cat Face', 'Creatures', {
    'K': 0xFF2B2B2B, 'O': 0xFFF4A261, 'L': 0xFFFFD6A5, 'G': 0xFF7CB518,
    'P': 0xFFFF8FA3,
  }, [
    '................',
    '..KK........KK..',
    '.KOOK......KOOK.',
    '.KOPOKKKKKKOPOK.',
    '.KOPOOOOOOOOPOK.',
    '.KOOOOOOOOOOOOK.',
    '.KOOOOOOOOOOOOK.',
    '.KOOGKOOOOGKOOK.',
    '.KOOGGOOOOGGOOK.',
    '.KOOOOOPPOOOOOK.',
    '.KOLOOOKKOOOLOK.',
    '.KOLLOOOOOOLLOK.',
    '..KOLLLLLLLLOK..',
    '...KKKKKKKKKK...',
    '................',
    '................',
  ]),
  Art('Rocket', 'Objects', {
    'K': 0xFF1B1B2F, 'W': 0xFFF1F1F1, 'G': 0xFFB8C0CC, 'R': 0xFFE63946,
    'B': 0xFF4CC9F0, 'F': 0xFFFF9F1C, 'Y': 0xFFFFE066, 'D': 0xFF8D99AE,
  }, [
    '.......KK.......',
    '......KRRK......',
    '.....KRRRRK.....',
    '.....KWWWWK.....',
    '....KWWWWWGK....',
    '....KWBBBBGK....',
    '....KWBBBBGK....',
    '....KWWBBGGK....',
    '....KWWWWWGK....',
    '..KRKWWWWWGKRK..',
    '.KRRKWWWWWGKRRK.',
    '.KRRKDDDDDDKRRK.',
    '....KDDDDDDK....',
    '.....KDDDDK.....',
    '......FYYF......',
    '.......FF.......',
  ]),
  Art('Fish', 'Creatures', {
    'K': 0xFF1B3A4B, 'B': 0xFF4CC9F0, 'D': 0xFF277DA1, 'L': 0xFFA8E6FF,
    'O': 0xFFF8961E, 'W': 0xFFFFFFFF,
  }, [
    '................',
    '......KKKKK.....',
    '...KKLLLLBBBKK..',
    '..KLLBBBBBBBBKOK',
    '.KLWKBBBBBBBKOOK',
    '.KLLBBBBBBBBKOOK',
    '.KDBBBBBBBBBKOOK',
    '..KDDBBBBBBBBKOK',
    '...KKDDDDDDKK...',
    '.....KKKKKK.....',
  ]),
  Art('Coffee Cup', 'Food', {
    'K': 0xFF3E2723, 'W': 0xFFF5F5F5, 'G': 0xFFBDBDBD, 'C': 0xFF6D4C41,
    'L': 0xFFA1887F, 'S': 0xFFDADADA,
  }, [
    '.....S...S......',
    '......S...S.....',
    '.....S...S......',
    '..KKKKKKKKKK....',
    '..KCCCCCCCCK....',
    '..KWWWWWWWWKKKK.',
    '..KWWWWWWWWKGGK.',
    '..KWWWWWWWWKGGK.',
    '..KGWWWWWWGKKKK.',
    '...KGWWWWGK.....',
    '....KKKKKK......',
    '..KKKKKKKKKKKK..',
    '...KGGGGGGGGK...',
    '....KKKKKKKK....',
  ]),
  Art('Ruby Gem', 'Objects', {
    'K': 0xFF4A0E17, 'H': 0xFFFFCCD5, 'L': 0xFFFF4D6D, 'R': 0xFFD90429,
    'D': 0xFF800F2F,
  }, [
    '..KKKK..',
    '.KHHLLK.',
    'KHLRRRDK',
    'KLRRRDDK',
    'KLRRRDDK',
    '.KLRDDK.',
    '..KRDK..',
    '...KK...',
  ]),
  Art('Mini Potion', 'Objects', {
    'K': 0xFF1C1917, 'C': 0xFF99582A, 'W': 0xFFD8F3DC, 'L': 0xFF52B788,
    'P': 0xFF2D6A4F, 'D': 0xFF1B4332,
  }, [
    '...CC...',
    '..KKKK..',
    '.KWLLPK.',
    'KWLLPPDK',
    'KWLPPPDK',
    'KLPPPDDK',
    '.KDDDDK.',
    '..KKKK..',
  ]),
  Art('Mini Dagger', 'Objects', {
    'K': 0xFF1E293B, 'W': 0xFFFFFFFF, 'S': 0xFFCBD5E1, 'D': 0xFF64748B,
    'G': 0xFFF59E0B, 'R': 0xFFEF4444, 'B': 0xFF78350F,
  }, [
    '...WW...',
    '...SWK..',
    '..KSDK..',
    '..KSDK..',
    '.GGGRGG.',
    '...BK...',
    '...BK...',
    '...GK...',
  ]),
  Art('Gold Coin', 'Objects', {
    'K': 0xFF78350F, 'W': 0xFFFFFBEB, 'L': 0xFFFEF08A, 'Y': 0xFFFCD34D,
    'D': 0xFFD97706,
  }, [
    '..KKKK..',
    '.KWLYDK.',
    'KWLLYYDK',
    'KWLYYDDK',
    'KLYYYDDK',
    'KLYDDDDK',
    '.KYDDDK.',
    '..KKKK..',
  ]),
  Art('Pixel Heart', 'Patterns', {
    'K': 0xFF4C0519, 'W': 0xFFFFFFFF, 'L': 0xFFFB7185, 'R': 0xFFE11D48,
    'D': 0xFF9F1239,
  }, [
    '........',
    '.KK..KK.',
    'KWLKKRDK',
    'KWLLRRDK',
    'KLLRRDDK',
    '.KLRDDK.',
    '..KRDK..',
    '...KK...',
  ]),
  Art('Mini Skull', 'Objects', {
    'K': 0xFF18181B, 'W': 0xFFFFFFFF, 'G': 0xFFE4E4E7, 'S': 0xFFA1A1AA,
    'D': 0xFF27272A,
  }, [
    '..KKKK..',
    '.KWGGSK.',
    'KWGGGGSK',
    'KWDKKDDK',
    'KWGGDGSK',
    '.KWGGSK.',
    '..KGSS..',
    '...KK...',
  ]),
  Art('Mini 1-Up', 'Nature', {
    'K': 0xFF14532D, 'G': 0xFF22C55E, 'D': 0xFF16A34A, 'W': 0xFFFFFFFF,
    'S': 0xFFE2E8F0, 'B': 0xFF0F172A,
  }, [
    '..KKKK..',
    '.KGWGDK.',
    'KGWWWGDK',
    'KGGGGGDK',
    '.KKKKKK.',
    '.KWBBWK.',
    '.KWSSSK.',
    '..KKKK..',
  ]),
  Art('Pixel Wizard', 'Characters', {
    'K': 0xFF1E1035, 'H': 0xFF581C87, 'P': 0xFF7E22CE, 'L': 0xFFA855F7,
    'D': 0xFF3B0764, 'F': 0xFFFFE4E6, 'C': 0xFF06B6D4, 'W': 0xFFE2E8F0,
    'S': 0xFF94A3B8, 'O': 0xFF22D3EE, 'B': 0xFF78350F, 'G': 0xFFFBBF24,
  }, [
    '......HH........',
    '.....HHHH.......',
    '....HPPLHH......',
    '...HPLLPPHH.....',
    '...HLLPPPPH.....',
    '..HGGGGGGGGH....',
    '...KFFFFFFK..OO.',
    '...KFCFFCK..OOOO',
    '..KWWWWWWK..OOOO',
    '.KWWSSWWSSK..OO.',
    '.HPPLPPPPPH..BK.',
    'HPPLLPPPPPPK.BK.',
    'HPLLPPGGPPPGBBK.',
    'HLLPPPGGPPPG.BK.',
    '.KPPPPDDPPPK.BK.',
    '..KKKK..KKKK....',
  ]),
  Art('Cyber Samurai', 'Characters', {
    'K': 0xFF0F172A, 'N': 0xFF1E293B, 'A': 0xFF334155, 'L': 0xFF64748B,
    'V': 0xFFF43F5E, 'P': 0xFFFDA4AF, 'G': 0xFF00F5D4, 'W': 0xFFFFFFFF,
    'Y': 0xFFFBBF24,
  }, [
    '......YY........',
    '.....YYYY.......',
    '....KNNNNK......',
    '...KNNLLNNK...W.',
    '...KVVVVVVK..GG.',
    '...KVPPVVVK..GG.',
    '...KNNNNNNK..GG.',
    '..KNNNAANNNK.GG.',
    '.KLNNAAAANNK.GG.',
    '.KNNNNAANNNK.GG.',
    '.KAAAAAAKKKK.GG.',
    '..KAAAAAAK...GG.',
    '..KNNAANNK...GG.',
    '..KNN..NNK...KK.',
    '..KNN..NNK...KK.',
    '..KKK..KKK......',
  ]),
  Art('Magical Campfire', 'Nature', {
    'K': 0xFF1C1917, 'W': 0xFFFEF9C3, 'Y': 0xFFFACC15, 'O': 0xFFFB923C,
    'R': 0xFFEF4444, 'P': 0xFFC084FC, 'B': 0xFF78350F, 'D': 0xFF451A03,
    'S': 0xFF64748B, 'L': 0xFF94A3B8,
  }, [
    '......PP........',
    '....P.YY...P....',
    '....YYWWYY......',
    '...YYWWWWYY.....',
    '..OYYWWWWYYO....',
    '..OYYYWWYYYO....',
    '.ROOYYYYYYOOR...',
    '.RROOOYYOOORR...',
    '.RRRROOOORRRR...',
    '..RRRROOOORR....',
    '.LL.BBBBBB.LL...',
    'SSSLBBDDDBBLSSS.',
    'SSSSBDDDDDDBSSSS',
    'SSSSKBBBBBBKSSSS',
    '.SSSSKKKKKKSSSS.',
    '..SSSSSSSSSSSS..',
  ]),
  Art('Golden Chest', 'Objects', {
    'K': 0xFF2A1810, 'G': 0xFFF59E0B, 'Y': 0xFFFDE047, 'W': 0xFF78350F,
    'R': 0xFF9A3412, 'E': 0xFF10B981, 'U': 0xFFEF4444, 'S': 0xFF06B6D4,
    'L': 0xFFFFFFFF,
  }, [
    '...KKKKKKKKKK...',
    '..KGGYYYYYYGGK..',
    '.KGGWWWRRWWWGGK.',
    '.KGWWWWWRRWWWGGK',
    'KGGGGGGGGGGGGGGK',
    'KG..L.E.U.S..GGK',
    'KG.LEEEEUUSSSGGK',
    'KGGEEEEEUUUSSGGK',
    'KGGGGGGYYYYGGGGK',
    'KGRRRRRRYYRRRRGK',
    'KGRWWWWWYYWWWRGK',
    'KGRWWWWKYYKWWWRK',
    'KGRRRRRKYYKRRRRG',
    'KGRWWWWWYYWWWRGK',
    'KGGGGGGGGGGGGGGK',
    '.KKKKKKKKKKKKKK.',
  ]),
  Art('Arcade Gamepad', 'Objects', {
    'K': 0xFF09090B, 'C': 0xFF71717A, 'L': 0xFFA1A1AA, 'D': 0xFF3F3F46,
    'S': 0xFF0284C7, 'G': 0xFF38BDF8, 'B': 0xFF18181B, 'R': 0xFFEF4444,
    'Y': 0xFFFBBF24, 'W': 0xFFFFFFFF,
  }, [
    '................',
    '...KKKKKKKKKK...',
    '..KLLLLLLLLLLK..',
    '.KLCGGGGGGGGCK..',
    '.KLCGGGGGGGGCK..',
    '.KLCSSSSSSSSCK..',
    '.KLCSSSSSSSSCK..',
    '.KCCCCCCCCCCDK..',
    '.KC.B...R.Y.DK..',
    '.KCBBC...R.YDK..',
    '.KC.B..WW...DK..',
    '.KCCCCCCCCCCDK..',
    '..KDDDDDDDDDDK..',
    '...KKKKKKKKKK...',
    '................',
    '................',
  ]),
  Art('Sushi Roll', 'Food', {
    'K': 0xFF0F172A, 'N': 0xFF1E293B, 'W': 0xFFF8FAFC, 'R': 0xFFCBD5E1,
    'S': 0xFFF97316, 'L': 0xFFFDBA74, 'A': 0xFF84CC16, 'C': 0xFF10B981,
    'G': 0xFFE2E8F0,
  }, [
    '....KKKKKKKK....',
    '..KKNNNNNNNNKK..',
    '.KNNNKKKKKKNNNK.',
    '.KNNKWRWWRWWKNN.',
    'KKNKRWWWRRWWKNKK',
    'KNNRWWSLLSWRWNNK',
    'KNNRWSSLLSSRWNNK',
    'KNNRWAASSRRWNNK.',
    'KNNRWAACCRRWNNK.',
    'KNNRWWCCCCRWNNK.',
    'KKNKRWWWRRWKNKK.',
    '.KNNKWRWRWWKNN..',
    '.KNNNKKKKKKNNNK.',
    '..KKNNNNNNNNKK..',
    '....KKKKKKKK....',
    '................',
  ]),
  Art('Crystal Butterfly', 'Creatures', {
    'K': 0xFF0F172A, 'B': 0xFF06B6D4, 'L': 0xFF67E8F9, 'W': 0xFFECFEFF,
    'P': 0xFFA855F7, 'D': 0xFF6B21A8, 'Y': 0xFFFDE047, 'C': 0xFF1E293B,
  }, [
    '.Y............Y.',
    '..K..........K..',
    '...K..KKKK..K...',
    '.KKKKBLLLLBK....',
    'KBLLBWLLLLBKKKK.',
    'KBLWWBBBBLLLLLBK',
    'KBLLBPPDPPBBLLBK',
    '.KLLBPPDDPBLLBK.',
    '..KKBPPDDDPKBK..',
    '.KBLLBPDPPBLLBK.',
    'KBLLWBBDPPBWLLBK',
    'KBLWWBBCCBBWWLBK',
    '.KBBB..CC..BBBK.',
    '..KB...CC...BK..',
    '...K...KK...K...',
    '................',
  ]),
  Art('Battle Mech', 'Characters', {
    'K': 0xFF09090B, 'S': 0xFF334155, 'A': 0xFF475569, 'H': 0xFF64748B,
    'D': 0xFF1E293B, 'G': 0xFF06B6D4, 'W': 0xFFE0F2FE, 'Y': 0xFFEAB308,
    'R': 0xFFEF4444, 'J': 0xFF71717A,
  }, [
    '........KKKKKKKK........',
    '.......KHHAAAAAHK.......',
    '......KHAAAAAAAADK......',
    '.....KSDGGGGGGGGDSK.....',
    '....KSAAWWWGGGGGAASK....',
    '....KSDDDDDDDDDDDSK.....',
    '..KKKRRKAAAAAAAAKRRKKK..',
    '.KYKKRRKAAHHAAAAKRRKKYK.',
    '.KYKKKKKAAAAAAAAKKKKKYK.',
    '.KYKSSSSJAAAAAAJSSSSSKY.',
    '.KKKSDDAJAAAAAAJADDDSKKK',
    '...KSDAAKJJJJJJKAADSK...',
    '...KSDDAKAAAAAAKADDDSK..',
    '...KSDDAKAYYYYAKADDDSK..',
    '....KKKKKAYYYYAKKKKK....',
    '........KAAAAAAK........',
    '.......KJAAAAAAJK.......',
    '......KSSK....KSSK......',
    '.....KSSAAK..KSSAAK.....',
    '.....KSDDAK..KSDDAK.....',
    '....KSAAHDK..KSAAHDK....',
    '....KSDDDK....KSDDDK....',
    '...KHHHHHDK..KHHHHHDK...',
    '...KKKKKKKK..KKKKKKKK...',
  ]),
  Art('Castle Fortress', 'Background', {
    'K': 0xFF0F172A, 'S': 0xFF475569, 'L': 0xFF64748B, 'D': 0xFF334155,
    'B': 0xFF1E293B, 'R': 0xFFDC2626, 'Y': 0xFFFBBF24, 'W': 0xFFFEF08A,
    'O': 0xFF78350F, 'I': 0xFF94A3B8, 'G': 0xFF15803D,
  }, [
    '......RRR...............',
    '......RRRR..............',
    '......RYRR..............',
    '......R.................',
    '.K.K..K....K.K....K.K...',
    '.KSK.KSK..KSSSK..KSK.KSK',
    'KLLLLLLLKKLLLLLKKLLLLLLK',
    'KLDSSDSLKLDSSDSLKLDSSDSL',
    'KSSDDDSSKSSDDDSSKSSDDDSS',
    'KLLSSSSLKLLSSSSLKLLSSSSL',
    'KLSSGSSLKLLSSSSLKLLSSSSL',
    'KSSGGDSSKSSDDDSSKSSDDDSS',
    'KLLGSSSLKLSWWSSLKLLSSSSL',
    'KLSSGSSLKSSWWSSSKLSSGSSL',
    'KSSDDGSSKSSDDBSSKSSDGSSS',
    'KLLSSGSLKSSSSSSSKLLSGSSL',
    'KLSSDDSLKSSBBBSSKLSSDDSL',
    'KSSSSSSKSOOOOOOSKSSSSSSK',
    'KLSSSSLKSIOIIOISKLSSSSSL',
    'KSSDDSSKSIOIIOISKSSDDSSK',
    'KLSSSSLKSIOIIOISKLSSSSLK',
    'KSSSSSSKSOOOOOOSKSSSSSSK',
    'KDDDDDDDDDDDDDDDDDDDDDDK',
    'KKKKKKKKKKKKKKKKKKKKKKKK',
  ]),
  Art('Cyberpunk Skyline', 'Background', {
    'K': 0xFF0A0A16, 'N': 0xFF18182E, 'M': 0xFF272953, 'C': 0xFF00F5D4,
    'P': 0xFFF72585, 'Y': 0xFFFEE440, 'O': 0xFFFF70A6, 'B': 0xFF4361EE,
    'S': 0xFF3A0CA3, 'R': 0xFFEF4444, 'W': 0xFFFFFFFF,
  }, [
    'SSSSSSSSSSSSSWWSSSSSSSSS',
    'SSSSSS.SSSSSSWWSSSSSS.SS',
    'BBBBBBBBBBBBBBBBBBBBBBBB',
    '.......R................',
    '.......K................',
    '.......K.....KKKKK......',
    '...KKKKK....KMMMMMK.....',
    '..KMMMMK....KMCMMMK.....',
    '..KMCPMK....KMMMMMK..KKK',
    '..KMMMMK.KKKKMCMMMK.KNMK',
    '..KMCPMK.KNMKMMMMMK.KPCK',
    '..KMMMMK.KPCKMCMMMK.KNMK',
    '.KKMMMMK.KNMKMMMMMK.KPCK',
    '.KMMMMMK.KPCKMCMMMK.KNMK',
    '.KMPPPPK.KNMKMMMMMK.KPCK',
    '.KMYYYYK.KPCKMCMMMK.KNMK',
    '.KMPPPPK.KNMKMMMMMK.KPCK',
    '.KMMMMMK.KPCKMCMMMK.KNMK',
    '.KMMMMMK.KNMKMMMMMK.KPCK',
    '.KMMMMMK.KPCKMCMMMK.KNMK',
    '.KCCCCCC.KNMKCCCCCC.KPCK',
    'KKKKKKKK.KPCKKKKKKK.KNMK',
    'NNNNNNNN.KNMKNNNNNN.KPCK',
    'KKKKKKKKKKKKKKKKKKKKKKKK',
  ]),
  Art('Cozy Cafe Window', 'Background', {
    'K': 0xFF1C1917, 'B': 0xFF991B1B, 'M': 0xFFB91C1C, 'D': 0xFF7F1D1D,
    'A': 0xFFDC2626, 'W': 0xFFFEF3C7, 'F': 0xFF78350F, 'G': 0xFFFEF08A,
    'H': 0xFFFDE047, 'C': 0xFF451A03, 'P': 0xFF15803D, 'R': 0xFFE11D48,
    'S': 0xFF94A3B8,
  }, [
    'BBMBBDBBMBBDBBMBBDBBMBBD',
    'DDBBMBBDBBMBBDBBMBBDBBMB',
    'KKKKKKKKKKKKKKKKKKKKKKKK',
    'KAAAAWWAAAAWWAAAAWWAAAAK',
    'KAAAAWWAAAAWWAAAAWWAAAAK',
    'KAAAAWWAAAAWWAAAAWWAAAAK',
    'KKKKKKKKKKKKKKKKKKKKKKKK',
    'BBKFFFFFFFFFFFFFFFFKKMBB',
    'DDKFGGGGGGGGGGGGGGGGFFKB',
    'BBKFGGGSGGGGGGGGGGGGFFKD',
    'DDKFGGGGSGG..W..WGGFFFKB',
    'BBKFGGGGSGG..W..WGGFFFKM',
    'DDKFGGGGGGG..CCC.GFFFFKB',
    'BBKFFFFFFFFFCCCFFFFFFKBD',
    'DDKFGGGGGGGFCCCCGGGGFFKB',
    'BBKFGGGSGGGGFFFFFGGGFFKM',
    'DDKFGGGGSGGGGGGGGGGGFFKB',
    'BBKFFFFFFFFFFFFFFFFFFKBD',
    'DDKKKKKKKKKKKKKKKKKKKKBB',
    'BBKPPRPPRPPRPPRPPRPPRKMB',
    'DDKPPRPPRPPRPPRPPRPPRKBD',
    'BBKFFFFFFFFFFFFFFFFFFKBB',
    'DDKKKKKKKKKKKKKKKKKKKKMB',
    'BBMBBDBBMBBDBBMBBDBBMBBD',
  ]),
  Art('Dragon Boss', 'Creatures', {
    'K': 0xFF2D0A0A, 'R': 0xFFDC2626, 'C': 0xFFB91C1C, 'L': 0xFFEF4444,
    'H': 0xFFF87171, 'B': 0xFF7F1D1D, 'Y': 0xFFFBBF24, 'O': 0xFFF97316,
    'W': 0xFFFFFFFF, 'N': 0xFFD97706, 'M': 0xFFFDE68A, 'S': 0xFF1C1917,
  }, [
    '....................MM..........',
    '...................MNM..........',
    '..................MNNM..........',
    '.................KNNNK..........',
    '................KNNNNK..........',
    '...............KNNNNK...........',
    '....KKKKKK....KNNNNK............',
    '...KHHHHHHK..KNNNNK.............',
    '..KHLLLLLLHKKNNNNK..............',
    '.KHLRRRRRRRKKNNNK...............',
    '.KLRRRRRRRRRKNNK...KKKKKK.......',
    'KLRRRRRRRRRRKKK...KHHHHHHK......',
    'KLRRRRRRLLLLRRK..KHLLLLLLHK.....',
    'KLRRRRRRLLLLRRK.KHLLRRRRRRHK....',
    'KLRRRRRYSYRRRRKKHLLRRRRRRRRK....',
    'KLRRRRRYSYRRRRKLLLRRRRRRRRRK....',
    'KLRRRRRRRRRRRKLLLRRRRRRRRRRK....',
    'KBLRRRRRRRRRKLLLLRRRRRRRRRRK....',
    '.KBLRRRRRRRKLLLLRRRRRRRRRRRK....',
    '.KBLLRRRRRKLLLLRRRRRRRRRRRRK....',
    '..KBLLLLLKLLLLRRRRRRROOORRRK....',
    '...KBBBBKLLLLRRRRRRROYYOORRK....',
    '....KKKKKLLLRRRRRRROYYYYOOK.....',
    '.....KLLLRRRRRRRRROOYYYWWK......',
    '....KLLLRRRRRRRRRKKKKKKKK.......',
    '...KLLLRRRRRRRRKK...............',
    '..KLLLRRRRRRRKK.................',
    '.KLLLRRRRRRKK...................',
    'KLLLRRRRRKK.....................',
    'KLLRRRRKK.......................',
    'KLRRRKK.........................',
    'KKKKK...........................',
  ]),
  Art('Starfighter', 'Objects', {
    'K': 0xFF0B132B, 'W': 0xFFF8FAFC, 'A': 0xFFCBD5E1, 'S': 0xFF64748B,
    'D': 0xFF334155, 'C': 0xFF00F5D4, 'B': 0xFF0284C7, 'G': 0xFF38BDF8,
    'L': 0xFFE0F2FE, 'R': 0xFFEF4444, 'Y': 0xFFFBBF24,
  }, [
    '...............KK...............',
    '..............KWWK..............',
    '..............KWWK..............',
    '.............KAWWAK.............',
    '.............KAWWAK.............',
    '............KSAWWASK............',
    '............KSGLLGSK............',
    '...........KSGGLLGGSK...........',
    '...........KSGGLLGGSK...........',
    '..........KSSGGLLGGSSK..........',
    '..........KSSGGLLGGSSK..........',
    '..........KSSSDDDDSSSK..........',
    '.........KSSSAWWWWASSSK.........',
    '.........KSSSAWWWWASSSK.........',
    '........KSSSSAAYYAASSSSK........',
    '........KSSSSAAYYAASSSSK........',
    '.......KSSSSSAWWWWASSSSSK.......',
    '..KK..KSSSSSSAWWWWASSSSSSK..KK..',
    '.KRK..KSDDDDDAWWWWADDDDDSK..KRK.',
    '.KRK.KSDDDDDDSDDDDSDDDDDDSK.KRK.',
    '.KSKKSDDDDDDDSDDDDSDDDDDDDSSKSK.',
    'KSWWKSSSSSSSSSDDDDSDSSSSSSSSKWWK',
    'KSWWKSSSSSSSSSDDDDSDSSSSSSSSKWWK',
    'KSWWKSSSAAAAASDDDDSAAAAASSSSKWWK',
    'KSAAKAAAWWWWWKDDDDDKWWWWWAAAKAAK',
    '.KSSKAAAWWWWWKDDDDDKWWWWWAAAKSSK',
    '..KKKAAAWWWWWKKKKKKKWWWWWAAAKKK.',
    '....KSAAWWWWWK.....KWWWWWASK....',
    '....KSSSSSSSSK.....KSSSSSSSK....',
    '.....KBBBBBBK.......KBBBBBBK....',
    '......KCCCCK.........KCCCCK.....',
    '.......KKKK...........KKKK......',
  ]),
  Art('Paladin Knight', 'Characters', {
    'K': 0xFF0F172A, 'S': 0xFF64748B, 'A': 0xFF94A3B8, 'H': 0xFFE2E8F0,
    'W': 0xFFFFFFFF, 'D': 0xFF334155, 'G': 0xFFF59E0B, 'Y': 0xFFFDE047,
    'Z': 0xFFB45309, 'B': 0xFF1D4ED8, 'L': 0xFF3B82F6, 'V': 0xFF1E3A8A,
    'F': 0xFFFFD7BA, 'R': 0xFFDC2626,
  }, [
    '..............BB................',
    '.............BLLBB..............',
    '............BLLLLBB.............',
    '...........BLLLLLLBB............',
    '..........BLLLLLLLLBB...........',
    '.........BLLLLLLVLLLVB..........',
    '........BLLLLLVVVLLLVVB.........',
    '.......BLLLLLVV.VVLLLVVB........',
    '.......BLLLVV....VLLLVVB........',
    '........BVVV..YY..VVLVB.........',
    '............KYYYYK..............',
    '...........KYGGGGYK.............',
    '..........KYGGRRGGYK............',
    '.........KYGGGRRGGGYK...........',
    '........KKHHHGGGGHHHKK..........',
    '.......KHAAHHHHHHHHAAHK.........',
    '......KHASSAHHHHHHAASSHK........',
    '......KHAASSDDDDDDSSAAGK........',
    '......KHAASKFKKKKFKSAAZK........',
    '......KHAASFDGGGGDFSAAZK........',
    '......KHAASFDYYYYDFSAAZK........',
    '......KHASSDDDDDDDDSSAAGK.......',
    '......KHAASSAAAAAASSSAAGK.......',
    '.....KHAASSDDDDDDDDSSAAGK.......',
    '...KKHAAASSDDDDDDDDSAAAGKKK.....',
    '..KBBHAASSAAAAAAAASSAAHGBBVK....',
    '.KBBBHAASSDDDDDDDDSAAAHGBBVVK...',
    '.KBBVHAASSDDDDDDDDSAAAHGBBVVK...',
    '.KBBVHHAASSAAAAAASSHAAHGBBVVK...',
    '.KVVVKKKAAADDDDDDAAAKKKVVVVVK...',
    '..KK..KKKAAAAAAAAKKK..KKKKK.....',
    '........KKKKKKKKKK..............',
  ]),
  Art('Cyber Hacker', 'Characters', {
    'K': 0xFF09090B, 'C': 0xFF00F5D4, 'B': 0xFF05B29B, 'W': 0xFFFFFFFF,
    'P': 0xFFF72585, 'M': 0xFFB5179E, 'J': 0xFF18181B, 'D': 0xFF27272A,
    'L': 0xFF3F3F46, 'S': 0xFF52525B, 'F': 0xFFFFD7BA, 'Y': 0xFFFEE440,
    'H': 0xFF71717A,
  }, [
    '.............CCCCCC.............',
    '...........CCCCCCCCC............',
    '..........CCCCCCCCCCC...........',
    '.........CCCCCCCCCCCCC..........',
    '........CCCCCCCCCCCCCCC.........',
    '.......CCCCWBCCCCCCBCCCC........',
    '......CCCCWWBBCCCCBBCCCCC.......',
    '.....CCCCWWBBBCCCCBBBCCCCC......',
    '.....CCCWBBBCCCCCCBBBCCCCCC.....',
    '....KHHHCBCCCCCCCCCCBCHHHK......',
    '....KHYHCBBBBBBBBBBBBCHYHK......',
    '...KHHYHKFFFFFFFFFFFFKHYHHK.....',
    '...KHHHHPPPPPPPPPPPPPPKHHHK.....',
    '...KHHHHPPWWWWPPWWWWPPKHHHK.....',
    '...KHHHHPPPPPPPPPPPPPPKHHHK.....',
    '....KKKKKFFFFFFFFFFFFKKKKK......',
    '.......KJJJJJJJJJJJJJJJJ........',
    '......KJDDDDDDDDDDDDDDDDJ.......',
    '.....KJDDPPPDDDDDDPPPDDDJ.......',
    '.....KJDDWWPDDDDDDWWPDDDJ.......',
    '.....KJDDMMMDDDDDDMMMDDDJ.......',
    '.....KJJJJJJJJJJJJJJJJJJJ.......',
    '....KLSSJJJJJJJJJJJJJJSSLK......',
    '...KLSSSSJJJJJJJJJJJJSSSSLK.....',
    '..KLSSSSSDJJJJJJJJJJDDSSSSSLK...',
    '..KLSSSSDCCCCJJJJCCCCDDSSSSSLK..',
    '.KLSSSSDCCCCCCJJCCCCCCDDSSSSSLK.',
    '.KLSSSDDJCCCCJJJJCCCCJDDDSSSSLK.',
    '.KLSSSDDJJJJJJJJJJJJJJDDDSSSSLK.',
    '.KLLLLDDJJJJJJJJJJJJJJDDDLLLLK..',
    '..KKKKKKJJJJJJJJJJJJJJJKKKKKK...',
    '.......KKKKKKKKKKKKKKKK.........',
  ]),
  Art('Floating Island', 'Nature', {
    'K': 0xFF0F172A, 'T': 0xFF15803D, 'L': 0xFF22C55E, 'H': 0xFF86EFAC,
    'D': 0xFF166534, 'W': 0xFF38BDF8, 'A': 0xFFBAE6FD, 'B': 0xFF0284C7,
    'R': 0xFF78350F, 'S': 0xFF475569, 'M': 0xFF64748B, 'V': 0xFF334155,
    'G': 0xFF1E293B, 'C': 0xFFE0F2FE, 'Y': 0xFFFEF08A,
  }, [
    '................................',
    '........HHHH....................',
    '.......HHLLLH......HHHH.........',
    '......HLLLLLLH....HLLLLH........',
    '.....HLLTTTTLLH..HLLTTLLH.......',
    '....HLLTTDDTTLLHHLLTTDDTLH......',
    '....HLTTDDDDDTTLLTTDDDDDTH......',
    '....HLTTDDDDDTTTTTDDDDDTH.......',
    '.....HLTTDDDDRRRRDDDDTTLH.......',
    '......HDDDDDDRRRRDDDDDTH........',
    '.......HDDDDRRRRRRDDDTH.........',
    '...........KRR..RRK.............',
    '...........KRR..RRK.............',
    '.........KKKRR..RRKKK...........',
    '......KKKLLLLRRRRLLLLKKK........',
    '....KKLLLLLLTTTTTTLLLLLLKK......',
    '...KLLTTTTTTTTTTTTTTTTTTLLK.....',
    '..KTTDDDDDDDDDDDDDDDDDDDDTTK....',
    '.KDDSSSSSSSSWAAWSSSSSSSSSBDDK...',
    '.KSSMMMMMMSSWAAWSSMMMMMMMSVVK...',
    '..KSMVVVVSSSWAAWSSMVVVVSSVVK....',
    '..KMVVSVVSSSWAAWSSSVVVSVVVK.....',
    '...KVVVVGGSSWAAWSSGGVVVVVK......',
    '....KVVGGGSSWAAWSSGGGVVVK.......',
    '....KGGGGGS.WAAW.SGGGGGK........',
    '.....KGGGGS.WAAW.SGGGGK.........',
    '......KGGGS.WAAW.SGGGK..........',
    '..CCC..KGGS.WAAW.SGGK...CCC.....',
    '.CCCCC..KGS.WAAW.SGK...CCCCC....',
    'CCCCCC...KG.WAAW.GK...CCCCCC....',
    '.CCCC.....K.BAAB.K.....CCCC.....',
    '............AAAA................',
  ]),
  Art('Arcade Cabinet', 'Objects', {
    'K': 0xFF09090B, 'C': 0xFF4F46E5, 'L': 0xFF818CF8, 'D': 0xFF312E81,
    'M': 0xFFF43F5E, 'W': 0xFFFFFFFF, 'S': 0xFF0284C7, 'G': 0xFF06B6D4,
    'P': 0xFF10B981, 'Y': 0xFFFBBF24, 'R': 0xFFEF4444, 'A': 0xFF52525B,
    'Z': 0xFF27272A, 'T': 0xFFF59E0B,
  }, [
    '.........KKKKKKKKKKKKKK.........',
    '........KLLLLLLLLLLLLLLK........',
    '.......KLCMMMMMMMMMMMMCLLK......',
    '......KLCMMWWMMWWMMWWMMMCLLK....',
    '......KLCMMMMMMMMMMMMMMMCLLK....',
    '......KKLLLLLLLLLLLLLLLLKKKK....',
    '......KCCLLLLLLLLLLLLLLCCK......',
    '.....KCCDKSSSSSSSSSSSSKDCCK.....',
    '....KCCDDKSGGGGGGGGGGKSKDCCK....',
    '....KCDDKSGG..Y....Y..SKSKDCCK..',
    '...KCCDDKSG....PP....GSKSKDCCK..',
    '...KCDDKSGG...PPPP...GSKSKDCCK..',
    '...KCDDKSGG..PPYYPP..GSKSKDCCK..',
    '...KCDDKSGGG.PPPPPP.GGSKSKDCCK..',
    '...KCDDKSGGGG..RR..GGGSKSKDCCK..',
    '...KCDDKSSSSSSSSSSSSSSKSKDCCK...',
    '...KCDDDKKKKKKKKKKKKKKDSKDCCK...',
    '...KCDDDAAAAAAAAAAAAAADSKDCCK...',
    '...KCDDDA..R...M.Y.M.ADSKDCCK...',
    '...KCDDDA.RRR..M.Y.M.ADSKDCCK...',
    '...KCDDDA..R...Y.M.Y.ADSKDCCK...',
    '...KCDDDAAAAAAAAAAAAAADSKDCCK...',
    '...KCDDDKKKKKKKKKKKKKKDSKDCCK...',
    '...KCDDDZZZZZZZZZZZZZZDSKDCCK...',
    '...KCDDDZZTTZZZZZZTTZZDSKDCCK...',
    '...KCDDDZZTTZZZZZZTTZZDSKDCCK...',
    '...KCDDDZZZZZZZZZZZZZZDSKDCCK...',
    '...KCDDDZZKKZZZZZZKKZZDSKDCCK...',
    '...KCDDDZZKKZZZZZZKKZZDSKDCCK...',
    '...KCDDDZZZZZZZZZZZZZZDSKDCCK...',
    '...KCDDDKKKKKKKKKKKKKKDSKDCCK...',
    '...KKKKKK............KKKKKKK....',
  ]),
  Art('Mystic Cauldron', 'Objects', {
    'K': 0xFF0A0A0A, 'I': 0xFF27272A, 'L': 0xFF52525B, 'D': 0xFF18181B,
    'M': 0xFFA855F7, 'P': 0xFFC084FC, 'C': 0xFF06B6D4, 'W': 0xFFF0ABFC,
    'B': 0xFF22D3EE, 'V': 0xFFE879F9, 'F': 0xFFEF4444, 'O': 0xFFF97316,
    'Y': 0xFFFDE047, 'S': 0xFF71717A,
  }, [
    '..........V...B.................',
    '.........VV..BBB....V...........',
    '........VV....B....VVV..........',
    '.........V...BBB...VV...........',
    '.........B....B.....V...........',
    '........BB....V.................',
    '.......BBB...VVV...B............',
    '........B.....V...BBB...........',
    '........WMM...WW...B............',
    '......WMMMMMWCPCCWMMW...........',
    '.....WMMMPPCCPPCCPMMMW..........',
    '...KKIILLLLLLLLLLLLLLIIKK.......',
    '..KIILPPPPMMCCCCCCMMPPPLIIK.....',
    '.KILPPCCCPPMCCCCCCPPMCCCPLLI....',
    '.KIPCCWCCPPMMCCCCMMMPCCWCCPIK...',
    '.KIPCCCCCCCCCCCCCCCCCCCCCCPIK...',
    '.KIIILLLLLLLLLLLLLLLLLLLLIIIIK..',
    '.KIILLLLLLLLLLLLLLLLLLLLLLIIIK..',
    'KIILLDDDDDDDDDDDDDDDDDDDDLLIIIK.',
    'KIILDDDDDDDDDDDDDDDDDDDDDDLIIIK.',
    'KIILDDDDDDDDDDDDDDDDDDDDDDLIIIK.',
    'KIILDDDDDDDDDDDDDDDDDDDDDDLIIIK.',
    'KIILDDDDDDDDDDDDDDDDDDDDDDLIIIK.',
    '.KIILLDDDDDDDDDDDDDDDDDDLLIIIK..',
    '..KIIILLLLDDDDDDDDDDLLLLIIIIK...',
    '...KKIIIIIILLLLLLLLIIIIIIKK.....',
    '....KKKIIIIIIIIIIIIIIIIKKK......',
    '......KKKKKKKKKKKKKKKKKK........',
    '.....SSSS.FFOOOOOOY.SSSS........',
    '....SSSSSFOOYYYYYYOOSSSSS.......',
    '...SSSSSSFOOOOOOOOOFSSSSSS......',
    '..SSSSSSSSFFFFFFFFFFSSSSSSS.....',
  ]),
  Art('Phoenix Bird', 'Creatures', {
    'K': 0xFF1C0606, 'R': 0xFFDC2626, 'D': 0xFF991B1B, 'O': 0xFFEA580C,
    'Y': 0xFFFACC15, 'W': 0xFFFEF08A, 'S': 0xFFFFFFFF, 'G': 0xFFF59E0B,
    'B': 0xFF7C2D12,
  }, [
    '...............WW...............',
    '..............WSSW..............',
    '.............WYYYYW.............',
    '.............WYYYYW.............',
    '............WYYYYYYW............',
    '...........WYYGGGYYW............',
    '...........WYGK.KGYYW...........',
    '..........WYYGGGGGYYW...........',
    '..........WYYYGGYYYYW...........',
    '.........WYYYYYYYYYYYW..........',
    '..YY....WYYYYROORYYYYYW....YY...',
    '.YYYY..WYYYYRROORRYYYYYW..YYYY..',
    'YYYYYY.WYYYRRROORRRYYYW.YYYYYY..',
    'YYOOYY.WYYRRRROORRRRYYW.YYOOYY..',
    '.YOOOYYWYYRRRROORRRRYYWYYOOOY...',
    '.YOOOOYWYRRRRROORRRRRYWYOOOOY...',
    '..YOOOORRRRRRROORRRRRRROOOOY....',
    '...YOOORRRRRRROORRRRRRROOOY.....',
    '....YOORRRRBRROORRBBRRROOY......',
    '.....YORRRBBRROORRBBRRROY.......',
    '......YRRBBBRROORRBBBRRY........',
    '......KRBBBBRROORRBBBBRK........',
    '......KRDDDDRROORRDDDDRK........',
    '.......KDDDDRROORRDDDDK.........',
    '........KDDDRROORRDDDK..........',
    '.........KDDRROORRDDK...........',
    '..........KDRROORRDK............',
    '...........KROOORK..............',
    '............KOOOK...............',
    '.............KOOK...............',
    '..............KOK...............',
    '...............K................',
  ]),
  Art('Forest Owl', 'Creatures', {
    'A': 0xFF243047,
    'B': 0xFFA26445,
    'C': 0xFFFFF1C7,
    'D': 0xFFFFFFFF,
    'E': 0xFF704734,
    'F': 0xFFD99B62,
    'G': 0xFFFFC857,
    'H': 0xFF8FCB77,
    'I': 0xFF56A36B,
    'J': 0xFF654234,
  }, [
    '........................',
    '........................',
    '........................',
    '.....A............A.....',
    '.....AA..........AA.....',
    '.....ABAA......AABA.....',
    '....AABBAAAAAAAABBAA....',
    '....AABCCCAAAACCCBAA....',
    '....ABCCCCCBBCCCCCBA....',
    '....ACCCDACCCCDACCCA....',
    '....ACCCAACCCCAACCCA....',
    '....ACCCAACCCCAACCCA....',
    '....AECCCCCFFCCCCCEA....',
    '....AEECCCGGGGCCCEEA....',
    '....AEEEFFFGGFFFEEEA....',
    '....AEEEFFFFGFFFEEEA....',
    '....ABEEFFEFFEFFEEBA....',
    '.....ABEFFFFFFFFEBA.HH..',
    '......ABBFFEFFFBBA..III.',
    '......AABBFFFFBBAA..I...',
    '.......AGGAAAAGGA..I....',
    '...JJJJJGGJJJJGGJJJJJ...',
    '...JJJJJJJJJJJJJJJJJJ...',
    '........................',
  ]),
  Art('Adventurer Lantern', 'Objects', {
    'A': 0xFF243047,
    'B': 0xFFFFC857,
    'C': 0xFFAD693B,
    'D': 0xFFBE803E,
    'E': 0xFF8A4B34,
    'F': 0xFFFFF4CA,
    'G': 0xFFFFE29A,
    'H': 0xFFEE8B3B,
    'I': 0xFFFFF1C7,
  }, [
    '........................',
    '........................',
    '........AAAAAAAA........',
    '........ABBBBBBA........',
    '........AB....BA....B...',
    '.......AAAAAAAAAA..BBB..',
    '......ACBBBBBBBCCA..B...',
    '......ACCCCCCCCCCA......',
    '.....AAAAAAAAAAAAAA.....',
    '...B.ABDDDDDDDDDDEA.....',
    '..BBBABDFFGGGGGGDEA.....',
    '...B.ABDFFGHGGBBDEA.....',
    '.....ABDFFGHGHBBDEA.B...',
    '.....ABDFFGHHHBBDEABBB..',
    '.....ABDFFHIIHBBDEA.B...',
    '.....ABDFFHIIHHBDEA.....',
    '.....ABDGGGIIHHBDEA.....',
    '.....ABDGGGGHGBBDEA.....',
    '.....ABDDDDDDDDDDEA.....',
    '.....AABBBBBBBBBBAA.....',
    '.....AAAAAAAAAAAAAA.....',
    '......AAAAAAAAAAAA......',
    '........................',
    '........................',
  ]),
  Art('Berry Basket', 'Food', {
    'A': 0xFF4B9D63,
    'B': 0xFF243047,
    'C': 0xFFFF91A0,
    'D': 0xFFE75164,
    'E': 0xFFFFF1C7,
    'F': 0xFFE4AC67,
    'G': 0xFFAE6B3E,
    'H': 0xFF754731,
  }, [
    '........................',
    '........................',
    '........................',
    '........................',
    '.............A..........',
    '.......A...AAA..........',
    '.....AAAAAAAAB....A.....',
    '..AAAAAB.BAAAB..AAA.....',
    '...BAAABBBCDDAAAAAB.....',
    '..BBCDDBBDDEDDBAAAB.....',
    '..BDDEDDBBDDDBBCDDBB....',
    '...BDDDB..BDBBDDEDDB....',
    '...BFFFFFFFFFFFFFFFFB...',
    '...BBBBBBBBBBBBBBBBBB...',
    '...BGFFHFFFHFFFHBFFGB...',
    '....BGGHGGGHGGGHGGGB....',
    '....BGGHGGGHGGGHGGGB....',
    '....BFFHFFFHFFFHFFFB....',
    '....BGGHGGGHGGGHGGGB....',
    '.....BGHGGGHGGGHGGB.....',
    '.....FFFFFFFFFFFFFF.....',
    '.....BBBBBBBBBBBBBB.....',
    '........................',
    '........................',
  ]),
  Art('Tiny Turtle', 'Creatures', {
    'A': 0xFF243047,
    'B': 0xFF559B68,
    'C': 0xFF83BF73,
    'D': 0xFF34725D,
    'E': 0xFFA6D981,
  }, [
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........AAAAAA..........',
    '.......AABBBCAA.........',
    '......ABCCCCCCBA.AAAA...',
    '.....ABCCDDDDCCBAEEEEA..',
    '....BBCCDDEEEDCAEEEEAEA.',
    '.BBBBBCDDDEEEEDAEEEEAEA.',
    '...BBBCCDEEEEDCAEEEEEBA.',
    '....BBCCDDDEDDCBAEEEEA..',
    '.....ABCCDDDDCCBAAAAA...',
    '.....AEABCCCCAAAA.......',
    '.....AEEEACBBAEEA.......',
    '.....AEEEAAAAAEEAA......',
    '.....AAAE.....AAAA......',
    '........A.....A.........',
    '........................',
    '........................',
    '........................',
  ]),
  Art('Friendly Robot', 'Characters', {
    'A': 0xFFEE7080,
    'B': 0xFF243047,
    'C': 0xFF7BA9B4,
    'D': 0xFFC6E7DF,
    'E': 0xFF557B8C,
    'F': 0xFF34475F,
    'G': 0xFF40C9AC,
    'H': 0xFFFFF1C7,
  }, [
    '........................',
    '...........AAA..........',
    '...........AAA..........',
    '............B...........',
    '............B...........',
    '.....BBBBBBBBBBBBBB.....',
    '.....BCDDDDDDDDDDCB.....',
    '....EBCFFFFFFFFFFCBE....',
    '....EBCFGGFFFFGGFCBE....',
    '....EBCFGGFFFFGGFCBE....',
    '....EBCFFFFHHHFFFCBE....',
    '.....BCCCCCCCCCCCCB.....',
    '.....BBBBBBBBBBBBBB.....',
    '....BBBBBBBBBBBBB.......',
    '....BBBBCDDDDDDCBBBBB...',
    '....BB.BCCCCCCCCBBBBB...',
    '....B..BCCFAAFCCB...BB..',
    '...BB..BCCFFFFCCB..CCC..',
    '..CCC..BCCCCCCCCB..CCC..',
    '..CCC..BBBBBBBBBB.......',
    '........BBB..BBB........',
    '........BBB..BBB........',
    '.......EEEE..EEEE.......',
    '........................',
  ]),
  Art('Moon Jellyfish', 'Creatures', {
    'A': 0xFFA6E9ED,
    'B': 0xFF243047,
    'C': 0xFFC59BF2,
    'D': 0xFFF0C8FF,
    'E': 0xFF917DD0,
    'F': 0xFF70CBD4,
  }, [
    '........................',
    '........................',
    '........................',
    '..A.......BBBB..........',
    '.......BBBCCCCBBB.......',
    '......BBCDDDDCCCCB......',
    '.....BBCDCCCCCCCCEB.....',
    '....BECDCCCCCCCCCCEB....',
    '....BCCCCCCCCCCCCCEB....',
    '...BEEEEBEEEEEEBEEEEB...',
    '...BEEEEBEEEEEEBEEEEB...',
    '...BFFFFFFFBBFFFFFFFB...',
    '...BFFFFFFFFFFFFFFFFB...',
    '......E...C...F..E......',
    '......E..C.....F.E......',
    '......E..C.....F.E......',
    '......E..C.....F.E...A..',
    '.......E..C...F.E.......',
    '..A.....E..C.F..E.......',
    '........E..C.F...E......',
    '.......E..C...F...E.....',
    '.......E..C...F.........',
    '..........C...F.........',
    '........................',
  ]),
  Art('Woodland Cabin', 'Background', {
    'A': 0xFF94C9BB,
    'B': 0xFFDCDFCC,
    'C': 0xFF39685B,
    'D': 0xFF71A078,
    'E': 0xFF243047,
    'F': 0xFFEFA574,
    'G': 0xFFB97953,
    'H': 0xFFD26F58,
    'I': 0xFF86543F,
    'J': 0xFFFFC857,
    'K': 0xFFBB6D3E,
    'L': 0xFF4E8067,
    'M': 0xFF694C42,
    'N': 0xFF365C56,
    'O': 0xFFE57879,
    'P': 0xFFD8A873,
    'Q': 0xFFC9AD79,
    'R': 0xFFF0D4A0,
  }, [
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAABBACAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAACAAAA',
    'AACAAAAAAAAAAAAAAAAAAABBAACDCAAA',
    'AACAAAAAAAAAAAAAEAAAAAAAAACDCAAA',
    'ACDCAAAAAAAAAAAEEEAAAAEEECDCCCAA',
    'ACDCAAAAAAAAAAEEFEEAAAEGECDCCCAA',
    'CDCCCAAAAAAAAEFFHFEEEAEGEDCCCCCA',
    'CDCCCACAAAAAEFHHHHFFEEEGEDCCCCCA',
    'DCCCCCCAAAAEFHHHHHHHFEEGECCCCCCC',
    'DCCCCCDCAAEHHHHHHHHHHFHEECCCCCDC',
    'CCCCCCDCAEHHHHHHHHHHHHHHEECCCCDC',
    'CCCCCDCCEHHHHHHHHHHHHHHHHHECCDCC',
    'CCCCCDCEEEEEEEEEEEEEEEEEEEEECDCC',
    'CCCCDCCCCEIIIIIIIIIIIIIIIECCDCCC',
    'CCCCDCCCCEGGEEEEEGGGGGGGGECCDCCC',
    'CCCDCCCCCEGGEJKJEGGGGGGGGEADCCCC',
    'CCCDCCCCCEIIEJKJEIIEEEEEIECDCCCC',
    'LLCCCCCCCEGGEJKJEGGEMMMEGECCCCCC',
    'LLCCCCCCCEGGEEEEEGGEMMMEGECCCCCC',
    'LLCCCCCCCEIIIIIIIIIEMJMEIECCCCCC',
    'LCCCCCCCCEGGGGGGGGGEMMMEGECCCCCC',
    'LCCCCCCCCEGGGGGGGGGEMMMEGECCCCCC',
    'NNNNONNNNEIIIIIIIIIEMMMEIENNNNNN',
    'NNNNPPNNNEEEEEEEEEEEQQQQEENNNONN',
    'NNNNNNNNNNNNNNNNNNNQQRQQQNNNNPPN',
    'NNNNNNNONNNNNNNNNNQQQRQQQQNNNNNN',
    'NNNNNNNPPNNNNNNNNNQQRQQQQQNNNNNN',
    'NNNNNNNNNNNNNNNNNQQRQQQQQQQNNNNN',
    'NNNNNNNNNNNNNNNNQQQQQQQQQQQQNNNN',
  ]),
  Art('Sunset Lighthouse', 'Background', {
    'A': 0xFFF7B17F,
    'B': 0xFF87556A,
    'C': 0xFF243047,
    'D': 0xFFFFE0A1,
    'E': 0xFFBD6160,
    'F': 0xFFFFC857,
    'G': 0xFFA66943,
    'H': 0xFFDC8B84,
    'I': 0xFFFFF1C7,
    'J': 0xFF50889B,
    'K': 0xFFC86261,
    'L': 0xFF85B4B2,
    'M': 0xFFB3D1BC,
    'N': 0xFF367088,
    'O': 0xFF3C4856,
    'P': 0xFF6F7B73,
    'Q': 0xFF284D6B,
  }, [
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAABBAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAABAABBAAAAAAAAAAAAAACAAAAAAA',
    'AAAAADDDDDAAABBAAAAAAAACECAAAAAA',
    'AAAADDDDDDDABAABBAAAAACEEECAAAAA',
    'AAADDDDDDDDDAAAAAAAACEEEEEEECAAA',
    'AADDDDDDDDDDDAAAAAACCCCCCCCCCCAA',
    'AADDDDDDDDDDDAAAAAAACFFFGFFFCAAA',
    'HHDDDDDDDDDDDHHHHHHHCFFFGFFFCHHH',
    'HHDDDDDDDDDDDHHHHHHHCFFFGFFFCHHH',
    'HHDDDDDDDDDDDHHHHHHCCCCCCCCCCCHH',
    'HHHDDDDDDDDDHHHHHHHCCCCCCCCCCCHH',
    'HHHHDDDDDDDHHHHHHHHHHCIIIIICHHHH',
    'HHHHHDDDDDHHHHHHHHHHCCIIIIICCHHH',
    'JJJJJJJJJJJJJJJJJJJJCKKKKKKKCJJJ',
    'JJJJJJJJJJJJJJJJJJJJCKKKKKKKCJJJ',
    'LLLLLLLLLLLLLLLLLLLLCKKKKKKKCLLL',
    'LLMMMMMMLLLLLLLLLLLLCIIIIIIICLLL',
    'JJJJJJJJJJJJJJJJJJJJCIICCIIICJJJ',
    'JJJJJJJJJJJJJJJJJJJJCIICCIIICJJJ',
    'NNNNNNNNNNNNNNNNNNNNKKKKKKKKKNNN',
    'NNNNNNNNNNNNNNNNNNNCKKKKKKKKKCNN',
    'JJJJJJJJJJJJJMMMMMMCIIIIIIIIICJJ',
    'JJJJJJJJJJJJJJJJJJOCIIIIIIIIICOJ',
    'NNNNNNNNNNNNNNNNNOOCCCCCCCCCCCPO',
    'NNNNNNNNNNNNNNNNNOPPPPPPPPPPPPPP',
    'JJJJMMMMMMMMJJJJOOPPPPPPPPPPPPPP',
    'JJJJJJJJJJJJJJJOOPPPPPPPPPPPPPPP',
    'QQQQQQQQQQQQQQOOPOOOOOOOOOOOOOOO',
    'QQQQQQQQQQQQQQOOOOOOOOOOOOOOOOOO',
    'JJJJJJJJJJJJJOOOOOOOOOOOOOOOOOOO',
  ]),
  Art('Sky Airship', 'Background', {
    'A': 0xFF6A9DBE,
    'B': 0xFF243047,
    'C': 0xFFEFC28B,
    'D': 0xFF476979,
    'E': 0xFFB96E57,
    'F': 0xFF8D5049,
    'G': 0xFFD99367,
    'H': 0xFF9EC9CC,
    'I': 0xFFFFF1C7,
    'J': 0xFFE9EED5,
    'K': 0xFFAE7655,
    'L': 0xFFFFC857,
  }, [
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAABBBBBBBBBBBBBAAAAAAAAAA',
    'AAAAAAABBCCCCCCCCCCCCCBBAAAAAADA',
    'AAAABBBECFCCCCCCCCCCFCCEBBAAADDA',
    'AAABBECCCFCCCCCCCCCCFCCCCBBDDDDA',
    'AAABECCCCFCCCCCCCCCCFCCCCEDDDDDA',
    'AABEECCCFCCCCCCCCCCCCFCCCEEDDDDA',
    'AAABEGGGFGGGGGGGGGGGGFGGGGEDBAAA',
    'AAABEGGGFGGGGGGGGGGGGFGGGGDDDDDA',
    'AAAABEEEFEEEEEEEEEEEEFEEEEDDDDDA',
    'AAAABBBEEFEEEEEEEEEEFEEEBDDDDDDA',
    'AAAAAABBEEFEEEEEEEEFEEBBAAAADDDA',
    'AAAAAAAABBBBBBBBBBBBBBAAAAAAAADA',
    'AAAAAAAAAAABAAAAAAAABAAAAAAAAAAA',
    'AAAAAAAAAAABAAAAAAAABAAAAAAAAAAA',
    'HHHHHHHHHHHBBBBBBBBBBHHHHHHHHHHH',
    'HHHHHHHHHHBBBBBBBBBBBBBHHIHHHHHH',
    'HHHHHHHJJJJBKKLLKLLKKBHHHIHHHHHH',
    'HHHHHJJJJJJBKKLLKLLKKBHBBIBHHHHH',
    'HHJJJJJJJJJJBBBBBBBBBHHHHIHHHHHH',
    'HJJJJJJJJJJJBBBBBBBBBHHHHIHHJJJJ',
    'JJJJJJJJJJJJJJJJHHHHHHHHHHJJJJJJ',
    'JJJJJJJJJJJJJJJJHHHHHHHJJJJJJJJJ',
    'JJJJJJJJJJJJJJJJHHHHHHJJJJJJJJJJ',
    'JJJJJJJJJJJJJJJJHHHHHJJJJJJJJJJJ',
    'HHHHHHHHJJJJJJJJHHHHHJJJJJJJJJJJ',
    'HHHHHJJJJJJJJJJJJHHHHJJJJJJJJJJJ',
    'HHHHJJJJJJJJJJJJJHHHHJJJJJJJJJJJ',
    'HHHJJJJJJJJJJJJJJJJHHHHHHHHHHHHH',
  ]),
  Art('Glass Terrarium', 'Nature', {
    'A': 0xFF243047,
    'B': 0xFF5F9F9C,
    'C': 0xFF85C8BD,
    'D': 0xFFF3F6DB,
    'E': 0xFFC5E5D1,
    'F': 0xFF57966B,
    'G': 0xFFA9D28D,
    'H': 0xFFA3DED3,
    'I': 0xFF45775C,
    'J': 0xFF79B67B,
    'K': 0xFF416E60,
    'L': 0xFF80B97B,
    'M': 0xFF977858,
    'N': 0xFFD6BA83,
    'O': 0xFF7D8D7C,
  }, [
    '................................',
    '................................',
    '............AAAAAAAA............',
    '...........ABCCCCCCBA...........',
    '..........ACBCCCCCCBCA..........',
    '.........ACCDBEEEEBCCCA.........',
    '........ACCDEBEEEEBECCCA........',
    '.......ACCDEEEBEEEBEECCCA.......',
    '......ACCDEEEEBEEBEEEECCCA......',
    '.....ACCDEEEEEEBEBEEFEECCCA.....',
    '....ACCDEEEEEEEBFBFFFEEECCCA....',
    '...ACCCEEEEEEEEEBFFGFEEEECCCA...',
    '...ACDEEEFFFFEEEHFGFFEEEHECCA...',
    '...ACDEEEFGFFFEFHGFFEEEEHECCA...',
    '...ACDEEEEFGFFFFHFFEEEEEHECCA...',
    '...ACDEEEEFFGGFFHFEEEEEHEECCA...',
    '...ACCDEEEFFFFGIHJJJJJEHEECCA...',
    '...ACCDEEEEEEEFIHJJJJJEHEECCA...',
    '....ACDEEKLLKEIIHJJJJEEHECCA....',
    '....ACDEEKLLKEIJHJJJJEEEEMCA....',
    '....ACDEEKKKKMJJHJEEEEMMMMCA....',
    '....ACMMKKKKKKIIHMMMMMMMMNCA....',
    '....ACNNKKKKKKIIHMMMOOONNNCA....',
    '....ACMNNNNNNNNNHNNOOOOONMCA....',
    '....ACMNNNNNNNNNHNNNOOONNMCA....',
    '....AACCMNNNNNNNNNNNNNNMCCAA....',
    '......AACMMNNNNNNNNNNMMCAA......',
    '.......AACCMMMMMMMMMMCCAA.......',
    '.........ACCCCCCCCCCCCA.........',
    '..........AAAAAAAAAAAA..........',
    '................................',
    '................................',
  ]),
  Art('Koi Garden', 'Background', {
    'A': 0xFF41685E,
    'B': 0xFFB1BBA0,
    'C': 0xFF859784,
    'D': 0xFF243047,
    'E': 0xFF477F89,
    'F': 0xFF80C5B5,
    'G': 0xFF529C9E,
    'H': 0xFF88B56A,
    'I': 0xFFE88E99,
    'J': 0xFFFFD6A0,
    'K': 0xFFEE8761,
    'L': 0xFFFFF1C7,
    'M': 0xFF2D6D58,
    'N': 0xFFED9971,
  }, [
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AABBBCAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'ACCCCCCAAAAAADDDDDDAAAAAAAAAAAAA',
    'ACCCCCCAAADDDEEEEEEDDDAAAAABBBCA',
    'ACCCCCCAADEEEEEEEEEEEEDAAACCCCCC',
    'AACCCCADDEEFFFFFFFFFFEEDDACCCCCC',
    'AAAAAADDEFFGGGGGGGGGGEEEDDCCCCCC',
    'AAAAAADEFEGGGGGGGGGGGGEEEDACCCCA',
    'AAAAADEHIHHGGGGGGGGGGGGEEEDAAAAA',
    'AAAADDHHJJHHGGDDDDDGGGGGEEDDAAAA',
    'AAAADEHHJJGGGDDKKLLDGGGGGEEDAAAA',
    'AAAADEMHIHHGDDLKKLDLDGGGGEEDAAAA',
    'AAADEEGMMMMDLLLLLLDDGGGGGGEEDAAA',
    'AAADEEGGMMMDLLDDDDDGGGGGGGEEDAAA',
    'AAADEEGGGGGDLDGGGGGGGGGGGGEEDAAA',
    'AAADEEGGGGGDDGGGGGGGGGGGGGEEDAAA',
    'AAADEEGGGGGDGGGGDGGGGGGGGGEEDAAA',
    'AAADEEGGGGGGGDDDNDDDGGGGFGEEDAAA',
    'AAADEEGGGGGGDLLNNNNDGHHHHGEEDAAA',
    'AAAADEEGGGGDDLLNNNNDHHHHHHGDAAAA',
    'AAAADEEGGGGGDDNDDDDNDHHGGGGDAAAA',
    'AAAADDEFGGGGGDGGGGGDDHHHHGGDAAAA',
    'AAAAADEEFGGGGGGGGGGGDMMMMMGAAAAA',
    'AAAAAADEEFGGGGGGGGGGGGMMMDAAAAAA',
    'AAAABBDDEEFFFFGGGGGGGEEEDDBBBCAA',
    'AAACCCCDDEEEEGFFFFGEEEEDDCCCCCCA',
    'AAACCCCCCDEEEEEEEEEEEEDAACCCCCCA',
    'AAACCCCCCADDDEEEEEEDDDAAACCCCCCA',
    'AAAACCCCAAAAADDDDDDAAAAAAACCCCAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  ]),
  Art('Bonsai Sanctuary', 'Nature', {
    'A': 0xFF243047,
    'B': 0xFF83BC7E,
    'C': 0xFF498C69,
    'D': 0xFFA17B52,
    'E': 0xFFA5C989,
    'F': 0xFF88A878,
    'G': 0xFF57899B,
    'H': 0xFF8AC2C7,
    'I': 0xFF376277,
    'J': 0xFFBA986E,
    'K': 0xFF71564B,
  }, [
    '................................',
    '................................',
    '...............AAAAAA...........',
    '.............AABBBBBBAA.........',
    '............AACBBBBBBCAA........',
    '............ACCCCCCCCCCA........',
    '........AAAAAACCCCCCCAAAAAA.....',
    '......AABBBBBAACCCCCAABBBBAA....',
    '.....ACCBBBBBCCAAAAACCBBBBCCA...',
    '.....ACCCCCCCCCAAADACCCCCCCCA...',
    '......AACCCCCAA..AADAACCCCAA....',
    '........AAAAA.....ADAAAAAAA.....',
    '.........AAAAA.....AAA..........',
    '........ACBBBCA....AAD..........',
    '.......ACCBBBCCAA.AADD....B.....',
    '........ACCCCCA.AAADDD....B.....',
    '....B....AAAAA..AAADD...........',
    '....B...........ADDD............',
    '................ADD.............',
    '................ADD...EE........',
    '............FFFFFFFFFFFFF.......',
    '.........AAAAAAAAAAAAAAAAAA.....',
    '.........AAAAAAAAAAAAAAAAAA.....',
    '.........AGGHHHHHHHHHHHHGGA.....',
    '..........AGGGGGGGGGGGGGGA......',
    '..........AGGGGGGGGGGGGGGA......',
    '...........AIIIIIIIIIIIIA.......',
    '...........AAAAAAAAAAAAAA.......',
    '...AJJJJJJJJJJJJJJJJJJJJJJJJA...',
    '...AAAAAAAAAAAAAAAAAAAAAAAAAA...',
    '......KKK...............KKK.....',
    '......KKK...............KKK.....',
  ]),
  Art('Woodland Fox', 'Creatures', {
    'A': 0xFF243047,
    'B': 0xFFD77342,
    'C': 0xFFF6C3A2,
    'D': 0xFFFFF1C7,
    'E': 0xFFEF9859,
    'F': 0xFFA94E36,
  }, [
    '........................',
    '........................',
    '....A...............A...',
    '....AA.............AA...',
    '....ABA...........ABA...',
    '....ACBAA.......AABCA...',
    '....ACCBAAAAAAAAABCCA...',
    '....ACCCBAAAAAAABCCCA...',
    '....ACBBBBBBBBBBBBBCA...',
    '...ABBBBAABBBBBAABBBA...',
    '...ABDBBAABBBBBAABBDA...',
    '...ABDDDDDBBBBBDDDDA....',
    '..AABBDDDDDAAADDDDD.....',
    '..ABBBDDDDDAAADDDDA.....',
    '..ADBBBBDDDDDDDDBA......',
    '..ADDDBBBBDDDDEBAA......',
    '..ADDDBBBBBBBEEBA.......',
    '..ADDDDEEEEEEEEBA.......',
    '...ABEEEEEEEEEEAA.......',
    '....ABEEFFFFEAA.........',
    '.....AAAAAAEAA..........',
    '...........A............',
    '........................',
    '........................',
  ]),
  Art('Honey Bee', 'Creatures', {
    'A': 0xFF243047,
    'B': 0xFFC8EDF0,
    'C': 0xFFECF9ED,
    'D': 0xFFFFFFFF,
    'E': 0xFFFFC857,
    'F': 0xFFFFEAA0,
    'G': 0xFFFFF1C7,
    'H': 0xFFA96B3E,
  }, [
    '........................',
    '........................',
    '........................',
    '.........AA...AAA.......',
    '........ABBA.AACAA.AA...',
    '.......ABBBBAACDDAAAA...',
    '.......ABBBBACCDDAA.....',
    '.......ABBBBACCCCAA.....',
    '.......AAAAAAAAAAAA.....',
    '......AAAAEEEAAEEEA.....',
    '.....AAEAAFFFAAEEEEA....',
    '....AEEEAAEEEAAEEGAEA...',
    '...AAEEEAAEEEAAEEAAEA...',
    '.AAAAEEEAAEEEAAEEEEEA...',
    '...AAEEEAAEEEAAEEEEEA...',
    '....AEEEAAEEEAAEHHEEA...',
    '.....AAEAAEEEAAEEEAA....',
    '......AAAAEEEAAEEAA.....',
    '.......AAAAAAAAAAA......',
    '.......A.......A........',
    '.......A.......A........',
    '........................',
    '........................',
    '........................',
  ]),
  Art('Strawberry Cupcake', 'Food', {
    'A': 0xFF559268,
    'B': 0xFFE66883,
    'C': 0xFFFFF1C7,
    'D': 0xFF243047,
    'E': 0xFFFFECE6,
    'F': 0xFFF8D2DE,
    'G': 0xFFE99BB7,
    'H': 0xFFB96E8E,
    'I': 0xFFF3B4CA,
  }, [
    '........................',
    '............A...........',
    '...........AAAA.........',
    '..........AAAA..........',
    '..........BBBAB.........',
    '..........BBCBB.........',
    '.........DBBBBBD........',
    '........DDBBBBBDD.......',
    '........DEEBBBEED.......',
    '.......FDEEEEEEEDF......',
    '......FFDDCCEEEDDFF.....',
    '.....DFCCDDEEEDGGFFD....',
    '.....DFFFFFDDDFFFFFD....',
    '.....DDFFFFFFFFFFFDD....',
    '.....DHDDFFFFFFFDDHD....',
    '.....DHHIDDDDDDDHIHD....',
    '......DHIHHIHHIHHID.....',
    '......DHIHHIHHIHHID.....',
    '......DIHHIHHIHHIHD.....',
    '......DIHHIHHIHHIHD.....',
    '.......IHHIHHIHHID......',
    '.......DHHHHHHHHHD......',
    '.......DDDDDDDDDDD......',
    '........................',
  ]),
  Art('Garden Snail', 'Creatures', {
    'A': 0xFF243047,
    'B': 0xFFC98259,
    'C': 0xFFEAAE70,
    'D': 0xFF8F563F,
    'E': 0xFF96BD75,
    'F': 0xFFC6DA94,
  }, [
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '..........AAAA..........',
    '........AABBBBAA........',
    '.......ABBBCCCBBA.......',
    '......ABBCDDDDDCBA......',
    '......ABBCCCCCCDAA...AA.',
    '.....ABBCCCDDDCCAAA..AA.',
    '.....ABBCCDCCCDCDAA...A.',
    '.....ABBCDCDCCDCDAA...A.',
    '.....ABBBDCCDDCCDBAAAA..',
    '......ABBCDDCCDDBAAEEA..',
    '......ABBBBCDDBBBAAEEA..',
    '.......ABBBBBBBBAAAEEA..',
    '...AAAAAAAAAAAAAAAEAEEA.',
    '...AEEEEEEEEEEEEEEEEEEA.',
    '..AEEFFFFFFFFFFFFEEEEEA.',
    '...AEEEEEEEEEEEEEEEEAA..',
    '....AAAAAAAAAAAAAAAAA...',
    '........................',
    '........................',
  ]),
  Art('Rainbow Balloon', 'Objects', {
    'A': 0xFF243047,
    'B': 0xFFE47279,
    'C': 0xFFFFC857,
    'D': 0xFF8CCBAD,
    'E': 0xFFFFC6A2,
    'F': 0xFFB57C4D,
    'G': 0xFFE3B980,
  }, [
    '........................',
    '........................',
    '.......AAAAAAAAAA.......',
    '......ABBCCDDCCBBA......',
    '.....ABBBCCDDCCBBBA.....',
    '....ABBBCCCDDCCCBBBA....',
    '...ABBEBCCDDDDCCBBBBA...',
    '...ABBECCCDDDDCCCBBBA...',
    '...ABBECCCDDDDCCCBBBA...',
    '...ABBECCCDDDDCCCBBBA...',
    '...ABBECCCDDDDCCCBBBA...',
    '...ABBBCCCDDDDCCCBBBA...',
    '....ABBCCCDDDDCCCBBA....',
    '.....ABBCCDDDDCCBBA.....',
    '.....ABBCCCDDCCCBBA.....',
    '......ABBCCDDCCBBA......',
    '.......AACCDDCCAA.......',
    '........AAAAAAAA........',
    '........A......A........',
    '.........A....A.........',
    '........AFGGGGFA........',
    '........AFFFFFFA........',
    '........AAAAAAAA........',
    '........................',
  ]),
  Art('Arcane Spellbook', 'Objects', {
    'A': 0xFF243047,
    'B': 0xFF68568A,
    'C': 0xFFA18AC0,
    'D': 0xFF493E6B,
    'E': 0xFFFFC857,
    'F': 0xFF8EE5D5,
    'G': 0xFFFFF1C7,
    'H': 0xFFCBB997,
    'I': 0xFFAD916F,
  }, [
    '........................',
    '........................',
    '.......AAAAAAAAAAAA.....',
    '.....AABBBBBBBBBBBBA....',
    '....ABBCBBBBBBBBBDDBA...',
    '...AABBCBBBBBBBBBDDBA...',
    '...AABBCBBBBEBBBBDDBA...',
    '...AABBCBBBEEEBBBDDBA...',
    '...AABBCBBBEFEEBBDDBA...',
    '...AABBCBBEFGFEEBDDBA...',
    '...AABBCBBEFGFFEEDAEEA..',
    '...AABBCBEFFFFEEBDAEEA..',
    '...AABBCBBEFFFEBBDAAAA..',
    '...AABBCBBBEFEEBBDDBA...',
    '...AABBCBBBEEEBBBDDBA...',
    '...AABBCBBBBEBBBBDDBA...',
    '...AABBCEEBBBBBBBDDBA...',
    '...AABBCBBBBBBBBBBBBA...',
    '...AHABCBBBBBBAAAAAAA...',
    '...AAHABAAAAAAIIHHHHA...',
    '....AAHAIIHHHHAAAAAAA...',
    '......AHAAAAAA..........',
    '.......A................',
    '........................',
  ]),
  Art('Hidden Waterfall', 'Background', {
    'A': 0xFFA1C8B6,
    'B': 0xFF346854,
    'C': 0xFF76A471,
    'D': 0xFF658B73,
    'E': 0xFF47746A,
    'F': 0xFF70C4CF,
    'G': 0xFF354F52,
    'H': 0xFFC0F0E6,
    'I': 0xFF554C41,
    'J': 0xFFE9F8E6,
    'K': 0xFF469BB5,
    'L': 0xFF94A78B,
    'M': 0xFF3C889C,
    'N': 0xFFEDAB87,
    'O': 0xFF7CCED0,
    'P': 0xFFD5F7E3,
  }, [
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAABBBAAA',
    'AAABBBAAAAAAAAAAAAAAAAAAACCCCBAA',
    'AACCCCBAAAAAAAAAAAAAAAAABCCCCBBA',
    'ABCCCCBBADAAAAAAAAAAAAAABBBBBBBA',
    'ABBBBBBBDDDAAAAAAADAAAAABBBBBBBA',
    'EBBBBBBBDDDDDEEEDDDDDDDDDBBBBBBB',
    'DDBBBBBBDDDDFFFFFFFFFDDDDDBBCCCC',
    'DDDBCCCCBDDGFFHHHHFFFGDDDDIBCCCC',
    'DDDBCCCCBBGGFJHHHHFFFGGGGGIBBBBB',
    'DDDBBBBBBBGGFJHHHHFKFGGGGGIBBBBB',
    'GGGBBBBBBBGGFJHHHHFKFGGGGGIIBBBB',
    'GGGIBBBBBGGGFJHHHHFKFGGGGGIIGBBB',
    'GGGIIBBBGGGGFJHHHHFKFGGGGGIIGIIG',
    'GGGIIIIGGGGGFJHHHHFKFGGGGGGGGIIG',
    'GGGGGIIGGGGGFJHHHHFKFGGGGGGGGIIG',
    'GGGGGIIGGGGGFJHHHHFKFGGGGGGGGIIG',
    'GGGGGIIGGGGGFJHHHHFKFGGGGGGGGIIG',
    'GGGGGIIGGGGGFJHHHHFKFGGGGGGGGIIG',
    'GGGGGIIGGGGGFJHHHHFKFGGGGGGGGGGG',
    'GGGGGGGLLLGGFJHHHHFKFGGGGGGGGGGG',
    'GGGGGGLLLLLMMMMMMMMMMMGGGGGGNNGG',
    'GGGGGGGLLLMMMOOOOOOOOMMMMGGGGGGG',
    'GGNNGGMMMMOOOOOOOOOOOOOOMMMGGGGG',
    'GGGGGMMMMOPPOOOOOOOOOOOPPMMMGGGG',
    'AAALLLMMMOOOPPPPPPPPPPPOOMMMMAAG',
    'AALLLLLMMMOOOOOOOOOOOOOOMMLLLAAA',
    'AAALLLMMMMMMMOOOOOOOOMMMMLLLLLAA',
    'AAAAAAMMMMMMMMMMMMMMMMMMMMLLLAAA',
    'AAAAAAAAMMMMMMMMMMMMMMMMMAAAAAAA',
    'AAAAAAAAAAAMMMMMMMMMMMAAAAAAAAAA',
  ]),
  Art('Starlight Observatory', 'Background', {
    'A': 0xFF202B4C,
    'B': 0xFFFFF1C7,
    'C': 0xFFD9E8CE,
    'D': 0xFF243047,
    'E': 0xFFB6CBD1,
    'F': 0xFF647FA1,
    'G': 0xFF3E597E,
    'H': 0xFFA6C5CB,
    'I': 0xFF334864,
    'J': 0xFF263C53,
    'K': 0xFF9EB3BD,
    'L': 0xFF897E87,
    'M': 0xFFFFC857,
    'N': 0xFFA09C99,
    'O': 0xFF697582,
  }, [
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAABAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAACAAAAAAA',
    'AABAAAAAAAAAAAAAABAAAAACAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAACCAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAACCCAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAADCCDAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAADDEDDDAAAAA',
    'AAAAAAAAAAAAAADDDDDDDDEEEDDDAAAA',
    'AAAAAAAAAAADDDFFFGFFDEEEDADAAABA',
    'AAAAAAAAAADFFFFFFGFDEEEDAAAAAAAA',
    'AAAABAAAADFFHFFFFGDEEEDFDAAAAAAA',
    'AAAAAAAADFFHFFFFFDEEEDDFFDAAAAAA',
    'AAAAAAADDFFHFFFFFGFEDDFFFDDAAAAA',
    'AAAAAAADFFHFFFFFFGFFDFFFFFDAAAAA',
    'IIIIIIIDFFHFFFFFFGFFFFFFFFDIIIII',
    'IIIIIIIDFFHFFFFFFGFFFFFFFFDIIIII',
    'IIIIIIIFFFHFFFFFFGFFFFFFFFFIIIII',
    'IIIIIJIFFFFFFFFFFGFFFFFFFFFIIIII',
    'IIIIJJJFFFFFFFFFFGFFFFFFFFFIIIIJ',
    'IIIJJJJDKKKKKKKKKKKKKKKKKKDIIJJJ',
    'IJJJJJJDKKKKKKKKKKKKKKKKKKDJJJJJ',
    'JJJJJJJDDDDDDDDDDDDDDDDDDDDJJJJJ',
    'JJJJJJJJDLLLDMMDLLLLDDDLLDJJJJJJ',
    'JJJJJJJJDLLLDMMDLLLLDDDLLDJJJJJJ',
    'JJJJJJJJDLLLDDDDLLLLDDDLLDJJJJJJ',
    'JJJJJJJJDDDDDDDDDDDDDDDDDDJJJJJJ',
    'JJJJJJJJJNNNNNNNNNNNNNNNNNNJJJJJ',
    'JJJJJJJJJNNNNNNNNNNNNNNNNNNJJJJJ',
    'JJJJJJJOOOOOOOOOOOOOOOOOOOOOOJJJ',
    'JJJJJJJOOOOOOOOOOOOOOOOOOOOOOJJJ',
  ]),
  Art('Midnight Ramen Shop', 'Background', {
    'A': 0xFF24304E,
    'B': 0xFF243047,
    'C': 0xFFDAAB73,
    'D': 0xFF684857,
    'E': 0xFF694857,
    'F': 0xFFDB7072,
    'G': 0xFFF6CFA3,
    'H': 0xFFA66A53,
    'I': 0xFFFFF3C9,
    'J': 0xFFE9826E,
    'K': 0xFFF9D8A0,
    'L': 0xFFFFC857,
    'M': 0xFFC46863,
    'N': 0xFFFFF1C7,
    'O': 0xFF815849,
    'P': 0xFFCC9A71,
    'Q': 0xFF3C3D59,
    'R': 0xFFB68164,
    'S': 0xFF90787D,
  }, [
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAABBBBBBBBBBBBBBBBBBBBAAAAAA',
    'AAAAAABCCCCCCCCCCCCCCCCCCBAAAAAA',
    'AAAAAABCCDDCCDDCCCDDCCDDCBAAAAAA',
    'AABBBBBCCCCCCCCCCCCCCCCCCBBBBBAA',
    'AABEEEBBBBBBBBBBBBBBBBBBBBEEEBAA',
    'AABEEEEEEEEEEEEEEEEEEEEEEEEEEBAA',
    'AABEEEEEEEEEEEEEEEEEEEEEEEEEEBAA',
    'AABEEEEEEEEEEEEEEEEEEEEEEEEEEBAA',
    'ABFFFGFFFGFFFGFFFGFFFGFFFGFFFGBA',
    'ABFFFGFFFGFFFGFFFGFFFGFFFGFFFGBA',
    'ABFFFGFFFGFFFGFFFGFFFGFFFGFFFGBA',
    'ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA',
    'AABHHBBBIBBBBBBBBBIBBBBBBBBJJJAA',
    'AABHHBKKIKKKKKKKKKIKKKKKKKBJLJAA',
    'AABHHBKKKIKKKKKKKKKIKKKKKKBJLJAA',
    'AABHHBKMNNNNNMKKKMNNNNNMKKBJLJAA',
    'AABHHBKMMMMMMMKKKMMMMMMMKKBJLJAA',
    'AABHHBKKMMMMMKKKKKMMMMMKKKBJJJAA',
    'AABHHBOOMMMMMOOOOOMMMMMOOOBHHBAA',
    'AABHHBOOOOOOOOOOOOOOOOOOOOBHHBAA',
    'AABHPPPPPPPPPPPPPPPPPPPPPPPPHBAA',
    'QQBHPPPPPBBBPPPPPPPBBBPPPPPPHBQQ',
    'QQBHBBBBBBBBBBBBBBBBBBBBBBBBHBQQ',
    'QQBBBBBBBBBBBBBBBBBBBBBBBBBBBBQQ',
    'QQQQQQQRRRRRRRQQQRRRRRRRQQQQQQQQ',
    'QQSSSSSRRRRRRRQQQRRRRRRRQQQQQQQQ',
    'QQQQQQQQQQQQQQQQQQQQQQQQQQSSSSSQ',
    'QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ',
  ]),
  Art('Mushroom Cottage', 'Background', {
    'A': 0xFFA5CABC,
    'B': 0xFF243047,
    'C': 0xFFD76B65,
    'D': 0xFFFFF1C7,
    'E': 0xFFF6BA88,
    'F': 0xFFE9CC9C,
    'G': 0xFFFFC857,
    'H': 0xFFED9D97,
    'I': 0xFF79A480,
    'J': 0xFF856350,
    'K': 0xFFF2D1A0,
    'L': 0xFFC7A675,
    'M': 0xFF3D7358,
    'N': 0xFF477862,
    'O': 0xFFD4C3A0,
  }, [
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAABBBBBBBBBAAAAAAAAAAA',
    'AAAAAAAAAAABCCCCCCCCCBBAAAAAAAAA',
    'AAAAAAAAABBCCCCCCCCCCCBBAAAAAAAA',
    'AAAAAAAABBCDDDCCCCCCCCCCBBAAAAAA',
    'AAAAAAABBCDDDDDCCCCCCCCCCBBAAAAA',
    'AAAAAABBCCCDDDCCCCCCCDDDCCBBAAAA',
    'AAAAABCCCCCCCCCCCCCCDDDDDCCBAAAA',
    'AAAABCCCCCCCCCCCCCCCCDDDCCCCBAAA',
    'AAAABCDDDDCCCCCCDDCCCCCCCCCCCBAA',
    'AAAABCDDDDCCCCCDDDDCCCCCCCCCCBAA',
    'AAABCCCCCCCCCCCCDDCCCCCCCCCCCBAA',
    'AAABCEEEEEEEEEEEEEEEEEEEEEEEEBAA',
    'AAABBEEEEEEEEEEEEEEEEEEEEEEEEBAA',
    'AAAAAAAAAABFFFFFFFFFFFFBAAAAAAAA',
    'AAAAAAAAAABFFFFFFFFBBBFBAAAAAAAA',
    'AAAAAAAAAABFFFFFFFFBGBFBAAAAAAAA',
    'AAAAAAAAAABFFFFFFFFBBBFBAAAAAAAA',
    'AAAAAAAAAABFFBBBBBBFFFFBAAHAAAAA',
    'IIIIHIIIIIBFFBJJJJBFFFFBIKHKIIII',
    'IIIKHKIIIIBFFBJJJJBFFFFBIIHIIIII',
    'IIIIHIIIIIBLLBJJGJBLLLLBIIMIIIII',
    'IIIIMIIIIIBLLBJJJJBLLLLBIIMIIIII',
    'IIIIMIIHIIBLLBJJJJBLLLLBIIIIIIII',
    'IIIIIIKHKIBLLBJJJJBLLLLBIIIIIIII',
    'NNNNNNNHNNBBBBOOOOOBBBBBNNNNNNNN',
    'NNNNNNNMNNNNNOOOOOOONNNNNNNNNNNN',
    'NNNNNNNMNNNNOOOOOOOOONNNNNNNNNNN',
    'NNNNNNNNNNNOOOOOOOOOOONNNNNNNNNN',
    'NNNNNNNNNNOOOOOOOOOOOOONNNNNNNNN',
  ]),
  Art('Underwater Ruins', 'Background', {
    'A': 0xFF345E7C,
    'B': 0xFF438E99,
    'C': 0xFFB0E0D1,
    'D': 0xFF243047,
    'E': 0xFFA8C5B1,
    'F': 0xFF87A89D,
    'G': 0xFF487B7F,
    'H': 0xFF397F8C,
    'I': 0xFF91B5AA,
    'J': 0xFFBED1B7,
    'K': 0xFFEDBA7A,
    'L': 0xFF62AA8B,
    'M': 0xFFFFC857,
    'N': 0xFFB48B50,
    'O': 0xFFC7B480,
    'P': 0xFF688C86,
  }, [
    'AAABBBBAAAAAAAAAAAAABBBAAAAAAAAA',
    'AAABBBBAAAAAAAAAAAAABBBAAAAAAAAA',
    'AAABBBBAAAAAAAAAAAAABBBAAAAAAAAA',
    'AAAABBBBAAAAAAAAAAAABBBAAAAAAAAA',
    'AAAABBBBAAAAAAAAAAABBBBAAAAAAAAA',
    'AAAABBBBAAAAAAAAAAABBBBAAAAAAAAA',
    'AAAABBBBAAACCAAAAAABBBBAAAAAAAAA',
    'AAAABBBBBAACCAAAAAABBBAAAAAAAAAA',
    'AAAAABBBBAAAAAAAAAABBBAAAAAAAAAA',
    'AAAAABBBBAAAAAAAAAABBBDEEEEEDAAA',
    'AACCABBBBAAAAAAAAABBBBDEEEEEDAAA',
    'AACCABBBBDFFFFFFFGGFFFFDDDDDDAAA',
    'HHHHDEEEEDFFFFFGGGGFFFFDIJIDHHHH',
    'HHHHDEEEEDFFFFFGGFFFFFFDIJIDHHHH',
    'HHHHDDDDDDDDDDDDDDDDDDDDIJIDHHHH',
    'HHHHHDIJIDHHHHHHHHBBBBHDIJIDCCHH',
    'HHHHHDIJIDBHHHHHHHBBBBHDKJIDKCHH',
    'HHHHHDIJIDBHHHHHHBBBBBDKKKKKKHHH',
    'HHHHHDIJIDBHHHHHHCCBBKKKKKIKKHHH',
    'LLHHHDIJIDBHHHHHHCCBBBHDKJIDKLHH',
    'LLHHHDIJIDBBHHHHHBBBBHHDIJIDLLHH',
    'HLLHHDIJIDBBHHHHHBBBBHHDIJIDHLLH',
    'HLLHHDIJIDBBHHHHHBBBBHHDIJIDHLLH',
    'LLLHHDIJIDBBHDDDDDDDDHHDIJIDLLLH',
    'LLHHHDIJIDBBBDMMMMMMDHHDIJIDLLHH',
    'LLHHHDIIIDBBBDNNMMNNDHHDIIILLLHH',
    'LOOOPPPPPPPBBDNNMMNNDOPPPPPLLOOO',
    'LOOOPPPPPPPOODNNNNNNDOPPPPPPLOOO',
    'LLOOPPPPPPPOODDDDDDDDOPPPPPPLLOO',
    'LLOOOOOOOOOOOOOOOOOOOOOOOOOOLLOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
  ]),
  Art('Lunar Rover', 'Background', {
    'A': 0xFF202841,
    'B': 0xFFFFF1C7,
    'C': 0xFF99C8AA,
    'D': 0xFF629BA7,
    'E': 0xFFD9D3BA,
    'F': 0xFFB9C8C5,
    'G': 0xFF243047,
    'H': 0xFF7C9FBC,
    'I': 0xFF8CB9BD,
    'J': 0xFFD1E8DA,
    'K': 0xFFC58C5F,
    'L': 0xFFA1A0AB,
    'M': 0xFFFFC857,
    'N': 0xFF60728A,
    'O': 0xFFB5BEC1,
    'P': 0xFF777D92,
    'Q': 0xFFC7C2BF,
  }, [
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAABAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAACDDDAAAA',
    'AAABAAAAAAAAAAAAAAAAAAADCCCCDAAA',
    'AAAAAAAAAAAAAAAAAAAAAADDCCCDDDAA',
    'AAAAAAAAAAAAAAAAAAAAAADDCCCDDDAA',
    'AAAAAAAAAAAAAAAAABAAAADDDCCCCCAA',
    'AAAAAAAAAAAAAAAAAAAAAEEEEEECCDAA',
    'AAAAAAAAAAAAAAAAAAAAAAEEEEEDCAAA',
    'AAAAAABAAAAAAAAAAAAAAFEEEEDDAAAA',
    'AAAAAAAAAAAAAAAAAAAFFFFEEEAAAAAA',
    'AAAAAAAAAAAAAAAAAAFFFAAEAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAFAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAA',
    'AAAAAAAAAAAGHHHHHGAGAAAAAAAAAAAA',
    'AAAAAAAAAAAGGGGGGGAGAAAAAAAAAAAA',
    'AAAAAAAAGGGGGGGGGGGGGGGGGAAAAAAA',
    'AAAAAAAAGEIJJJJIEEKKKKKEGAAAAAAA',
    'AAAAAALAGEIIIIIIEEKMMMKEGLAAAAAA',
    'AAAALLLLGEIIIIIIEEKMMMKEGLGGGAAA',
    'AALLLLLLGEEEEEEEEEKKKKKEGGLLGLLL',
    'LLLLLLLLGEEGGEEEEEEEEEGGGLLLGLLL',
    'LLLLLLLLGGGNNGGGGGGGGGNNGLLEEELL',
    'LLLLLLLLGGNOONGGGGGGGNOONGPEEELL',
    'LLLLLLLLLGNOONGLLLLLGNOONGPPPPPL',
    'LLLLPPPPPLGNNGLLLLLLLGNNGPPPPPPL',
    'LLPQQQQQQPPGGLLLLLLLLLGGLPPPPLLL',
    'LLPPPPPPPPPLLLLLLLLLLLLLLLLLLLLL',
    'LLLLPPPPPLLLLLLLLLLLLLLLLLLLLLLL',
    'LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL',
    'LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL',
  ]),
  Art('Trail Adventurer', 'Characters', {
    'A': 0xFFAB7652,
    'B': 0xFF694739,
    'C': 0xFFEFBA91,
    'D': 0xFF243047,
    'E': 0xFFB7D8D4,
    'F': 0xFFE28252,
    'G': 0xFF5F9B89,
    'H': 0xFFC9AB6C,
    'I': 0xFFFFC857,
    'J': 0xFF3E5270,
  }, [
    '........................',
    '........................',
    '.........AAAAAB.........',
    '.......BBBBBBBBB........',
    '.......BBBBBBBBBB.......',
    '.......BBBBCCCBBB.......',
    '.......BBBBCDCBBB.......',
    '.......BDCCCCCD.B.......',
    '........DCCCCCD.....E...',
    '........DDDDDDD.....E...',
    '........FFFFFFFF....E...',
    '.......DFFFFFFFF....E...',
    '.....DDDDGHGGFFDDDD.E...',
    '.....CCDDHHHGFFDDCC.E...',
    '.....CCDDGHHHGGDDCC.E...',
    '....DCCDDGGGHBIIDCCDE...',
    '....DDDDDGGGGBBBDDDIII..',
    '......D.DDDDDBBBBD..B...',
    '........JJJ..JJJ....B...',
    '........JJJ..JJJ....B...',
    '........JJJ..JJJ........',
    '.......BBBB..BBBB.......',
    '.......BBBB..BBBB.......',
    '........................',
  ]),
  Art('Hooded Ranger', 'Characters', {
    'A': 0xFF243047,
    'B': 0xFF468573,
    'C': 0xFF2B5B54,
    'D': 0xFFFFDBB2,
    'E': 0xFFEFBA91,
    'F': 0xFFDED2B1,
    'G': 0xFFB78152,
    'H': 0xFFD6B67A,
    'I': 0xFF947246,
    'J': 0xFFFFC857,
    'K': 0xFF504844,
  }, [
    '........................',
    '........................',
    '.............A..........',
    '.......AAAAAABA.........',
    '.......ABBBBBBBAA.......',
    '.......ABCCCCCCAAA......',
    '......AABADDEEEABA..F...',
    '......ABBADAEAEABA..FG..',
    '......ABBAEEEEEABA..FG..',
    '.......BBAEEEEEABA..F.G.',
    '.......ABAAAAAAABA..F.G.',
    '......A.AAAAAAAAA...F..G',
    '.....AAAABBBBBBA....F..G',
    '...AEE..ABBBBBBAE...F..H',
    '....EE.ABBBBBBBBEHHHHHHH',
    '...AAA.ABBBBBBBBA..EF..H',
    '....AAAABBBBBBBBA...F.G.',
    '.....A.BIIIIJJIIB...F.G.',
    '......ABBBBBBBBBBA..F.G.',
    '......AAAAAAAAAAAA..FG..',
    '........KKK..KKK....FG..',
    '........KKK..KKK....F...',
    '........KKK..KKK........',
    '........................',
  ]),
  Art('Scarlet Pirate', 'Characters', {
    'A': 0xFF243047,
    'B': 0xFFE29169,
    'C': 0xFFFFF1C7,
    'D': 0xFFBD5C5D,
    'E': 0xFFEFBA91,
    'F': 0xFF694739,
    'G': 0xFFA54851,
    'H': 0xFFD5C6AA,
    'I': 0xFFB7D5CD,
    'J': 0xFFFFC857,
    'K': 0xFF425373,
  }, [
    '........................',
    '.............A.....BB...',
    '......A.....AAAA..B.....',
    '.....AAAAAAACCAAAB......',
    '.....AAAAAACCCCAAAA.....',
    '....AADDDDDDDDDDDDDAA...',
    '....AAAAAAAAAAAAAAAAA...',
    '........AAAAEAAA........',
    '........AAAAEEEA........',
    '........AEEEEEEA........',
    '........AAFFFFFA........',
    '.......G..FFFFF.........',
    '......GGGGHHHHHGG.G.....',
    '.....GGGGGHHHHHGGGGG....',
    '.....GG.GGHHHHHGG.GGG...',
    '.....GG.GGGGGGGGG..GG...',
    '....EEE.GGHHHHHGG..III..',
    '....EEE.FFFFJJFFF....I..',
    '........FFFFFFFFF..III..',
    '.........KKK..FF........',
    '.........KKK..FF........',
    '.........KKK..FF........',
    '........AAAA..AAA.......',
    '........................',
  ]),
  Art('Pastry Chef', 'Characters', {
    'A': 0xFF243047,
    'B': 0xFFFFF1C7,
    'C': 0xFFDED9C7,
    'D': 0xFFFFDBB2,
    'E': 0xFFEFBA91,
    'F': 0xFF697D8D,
    'G': 0xFFFFC857,
    'H': 0xFFE47C70,
    'I': 0xFFBDC9C4,
  }, [
    '.............AAAA.......',
    '........AAA.ABBBBA......',
    '.......ABBBBBBBBBBA.....',
    '......ABBBBBBBBBBBA.....',
    '......ABBBBBBBBBBBA.....',
    '.......ACCCCCCCCCA......',
    '.......ACCCCCCCCCA......',
    '........ADDEEEEA........',
    '........ADAEEAEA........',
    '........AEEEEEEA....AAA.',
    '........AEEEEEEA...AFGFA',
    '........AAAAAAAA...AFFFA',
    '.......BAHHHHHHHA...AAA.',
    '.....BBBAHHHHHHHABB..A..',
    '.....BB.ABBBIBABA.B.AAA.',
    '.....BB.ABBBIBBBA.BAAA..',
    '....BB..ABBBIBBBA.BEA...',
    '...EEE..ABBBIBABA.......',
    '...EEE..ABBBBBBBA.......',
    '........AAAAAAAAA.......',
    '..........AA..AA........',
    '..........AA..AA........',
    '..........AA..AA........',
    '........................',
  ]),
  Art('Orbital Astronaut', 'Characters', {
    'A': 0xFF243047,
    'B': 0xFFFFF1C7,
    'C': 0xFFC5EDE0,
    'D': 0xFF5A9FA8,
    'E': 0xFF3A647D,
    'F': 0xFF879AA7,
    'G': 0xFF708D9E,
    'H': 0xFFE17A70,
    'I': 0xFF40C9AC,
  }, [
    '........................',
    '........................',
    '........AAAAAAAA........',
    '.......ABBBBBBBBA.......',
    '......ABBBBBBBBBBA......',
    '.....ABBAAAAAAAABBA.....',
    '.....ABBACCCDDDABBA.....',
    '.....ABBADDDDDDABBA.....',
    '.....ABBADDDDDDABBA.....',
    '.....ABBADDDDEEABBA.....',
    '....AABBAAAAAAAABBA.....',
    '....AFABBBBBBBBBBA......',
    '....AFFABBBBBBBBA.......',
    '....AFFBAAAAAAAA........',
    '....AFBBBBBBBBBA.B......',
    '....AFBBABGGGGBABBB.....',
    '....ABBBABGHGIBA.BB.....',
    '....GGGAABGGGGBA.GGG....',
    '....GGGAABBBBBBA.GGG....',
    '........AAAAAAAA........',
    '........BBB..BBB........',
    '........BBB..BBB........',
    '.......AAAA..AAAA.......',
    '.......AAAA..AAAA.......',
  ]),
  Art('Midnight Ninja', 'Characters', {
    'A': 0xFF243047,
    'B': 0xFF4B547B,
    'C': 0xFFC76B79,
    'D': 0xFFEFBA91,
    'E': 0xFF353A5A,
    'F': 0xFFFFC857,
    'G': 0xFFB6D4D4,
    'H': 0xFF8389A7,
  }, [
    '........................',
    '........................',
    '............A...........',
    '.......AAAAABA..........',
    'C......ABBBBBBAA........',
    'CC....CCCCCCCCCC........',
    '.CCCCCCDDDDDDDDD........',
    '.CCCCCADDADDDADDA.......',
    '.CCCCCADDDDDDDDDA.......',
    '.......EEEEEEEEE..F.....',
    '.......EEEEEEEEE..GFGG..',
    '........AAAAAAA.GG.F....',
    '........AABBBBAG........',
    '.......AAHBBBBBAA.......',
    '......ABBBHHBBBAA.......',
    '.......ABBBBHBBBAA......',
    '.......ACCCCCCCCBAA.....',
    '........AAAABBBBAA......',
    '........A...AABAA.......',
    '........AAAAA.AA........',
    '...AAAAAAAAAAAAAAAAAA...',
    '...AAAAAAAA..AAAAAAAA...',
    '..AAAAAAAA....AAAAAAAA..',
    '........................',
  ]),
  Art('Forest Witch', 'Characters', {
    'A': 0xFF243047,
    'B': 0xFF546A6E,
    'C': 0xFF86D2B6,
    'D': 0xFFFFF1C7,
    'E': 0xFFC09965,
    'F': 0xFFFFC857,
    'G': 0xFFC0B4A4,
    'H': 0xFFFFDBB2,
    'I': 0xFFEFBA91,
    'J': 0xFF9C7851,
    'K': 0xFF78968B,
    'L': 0xFF334954,
  }, [
    '................................',
    '.................A..............',
    '...............AAA..............',
    '..............AAAB..............',
    '............AAAABBA.............',
    '............AABBBBA.............',
    '...........AAABBBBAA.....AAA....',
    '...........AABBBBBBAA...ACCCA...',
    '..........AAABBBBBBAA..ACDDCCA..',
    '..........EEEEEFFEEEEE.ACCCCCA..',
    '........ABEEEEEFFEEEEEAACCCCCA..',
    '......BBBBBBBBBBBBBBBBBBACCCA...',
    '....AAAAAAAAAAAAAAAAAAAAAAAA....',
    '...........GGHHIIIIIAGG...JJ....',
    '...........GGHAIIIAIAGG...JJ....',
    '...........GGIIIIIIIAGG...JJ....',
    '...........GGIIIIIIIA.G...JJ....',
    '..........GGAIIIIIIIA.GG..JJ....',
    '..........GGAAAAAAAAA.GG..JJ....',
    '..........GIAAAAAAAAAAGGI.JJ....',
    '..........IIIKBBBBBBBIIII.J.....',
    '........IIIAAKKBBBLBBIA..JJ.....',
    '.........I.AKKEEEFFEEBA..JJ.....',
    '..........AAKKEEEEEEEBAA.JJ.....',
    '..........ABKKKKBBBLBBAA.JJ.....',
    '.........AAKKKKKBBBLBBBA.JJ.....',
    '.........ABKKKKKKBBBLBBAAJJ.....',
    '........AAKKKKKKKBBBLBBBAJJ.....',
    '........ABKKKKKKKBBBBBBBAAJ.....',
    '.......AAAAAAAAAAAAAAAAAAAJ.....',
    '...........AAAA....AAAA.........',
    '...........AAAA....AAAA.........',
  ]),
  Art('Desert Nomad', 'Characters', {
    'A': 0xFF243047,
    'B': 0xFFD8C29D,
    'C': 0xFFFFDBB2,
    'D': 0xFFEFBA91,
    'E': 0xFFBED6D1,
    'F': 0xFFECD6AF,
    'G': 0xFFBD8462,
    'H': 0xFFB77C5B,
    'I': 0xFFDEB58A,
    'J': 0xFF845B4D,
    'K': 0xFFFFC857,
    'L': 0xFF4F656E,
  }, [
    '................................',
    '................................',
    '.............A..................',
    '..........AAAABAAAAAA...........',
    '..........ABBBBBBBBBBA..........',
    '..........ABBAAAAAABBBA.........',
    '.........ABBAAAAAAAABBBA........',
    '.........ABAACDDDDDDBBAA........',
    '.........AAAAADDDDADABA.........',
    '...........ADDDDDDDDA.A.........',
    '...........ADDDDDDDDA.A.....EE..',
    '...........AFFFFFFFFF.......EE..',
    '...........AGGGGGGGGG.......EE..',
    '...........AGGGGGGGGG......EE...',
    '..........AAAAAAAAAAAA.....EE...',
    '.........DAHIHHHHHHHHA.....EE...',
    '........DDDHIIHHHHHHJAAD..EEE...',
    '......DDDAHIIIIIHHHHJHDDDEEE....',
    '......DD.AHIIIIIHHHHHJAAKKE.....',
    '......DDAAHIIIIIHHHHHJAA.EKK....',
    '.....DD.AAHIIIIHHHHHHHJA........',
    '.....DD.AHIILLLLKKLLLHJAA.......',
    '........AHIILLLLLLLLLHJHA.......',
    '.......AAHIIIIIHHHHHHHHJA.......',
    '.......AAHIIIIHHHHHHHHHJAA......',
    '.......AHIIIIIHHAAHHHHHHHA......',
    '......AAHIIIIIAA..AHHHHHHAA.....',
    '......AAAAHAA......AHAAAAAA.....',
    '..........ALLLL....LLLL.........',
    '...........LLLL....LLLL.........',
    '...........LLLL....LLLL.........',
    '..........AAAAA....AAAAA........',
  ]),
  Art('Clockwork Engineer', 'Characters', {
    'A': 0xFFAB7851,
    'B': 0xFF694739,
    'C': 0xFF8FA7B5,
    'D': 0xFF243047,
    'E': 0xFFB78854,
    'F': 0xFF40C9AC,
    'G': 0xFFEFBA91,
    'H': 0xFFD1DDD4,
    'I': 0xFFC99467,
    'J': 0xFF55798B,
    'K': 0xFF9BB6B2,
    'L': 0xFFFFC857,
  }, [
    '................................',
    '................................',
    '................................',
    '............AAAAAAAA............',
    '..........BBAAAAAAAABB..CCC..CCC',
    '..........BBBBBBBBBBBB..CCC..CCC',
    '..........DEEEEDDEEEED..CCC..CCC',
    '..........DEFFEDDEFFED..CCCCCCCC',
    '..........DEEEEDDEEEED..CCCCCCCC',
    '...........DGGGGGGGGD....CCCCCC.',
    '...........DGGGGGGGGD.....CCCC..',
    '...........DGGGGGGGGD.....HC....',
    '...........DDDDDDDDDD.....HC....',
    '........I.DDDDDDDDDDDDD.I.HC....',
    '.......IIIDIJJIIIIIJJIDIIIHC....',
    '......IIIIIIJJIIIIIJJIIIIIHC....',
    '.....IIIIIDIJJJJJJJJJIDIIIHC....',
    '.....IIII.DIJJJJJJJJJID.IIHC....',
    '.....III..DIJJJKLLKJJID..ICC....',
    '.....III..DIJJJKKKKJJID.BBCC....',
    '.....III..DIJJJKKKKJJID.BBCC....',
    '....BBBB..DIJJJJJJJJJID.BBCC....',
    '....BBBB..DIJJJJJJJJJID...CC....',
    '....BBBB..DBBBBBBBBBBBD.........',
    '..........DBBBBBBBBBBBD.........',
    '..........DDDDDDDDDDDDD.........',
    '...........JJJJ...JJJJ..........',
    '...........JJJJ...JJJJ..........',
    '...........JJJJ...JJJJ..........',
    '...........JJJJ...JJJJ..........',
    '..........BBBBB...BBBBB.........',
    '..........BBBBB...BBBBB.........',
  ]),
  Art('Crystal Ice Mage', 'Characters', {
    'A': 0xFF243047,
    'B': 0xFFA7EAE6,
    'C': 0xFF72CFDB,
    'D': 0xFFE6FFF4,
    'E': 0xFF9EBDE0,
    'F': 0xFF5295C0,
    'G': 0xFFEFBA91,
    'H': 0xFFFFDBB2,
    'I': 0xFF839CDA,
    'J': 0xFF9DC4D1,
    'K': 0xFF536CB0,
    'L': 0xFF345288,
    'M': 0xFF40C9AC,
    'N': 0xFFC8E5E5,
  }, [
    '................................',
    '..........................A.....',
    '...B.....................ACA....',
    '..BBB........AAAAAA......CDC....',
    '...B........AEEEEEEA....ACFCA...',
    '..........AAEEEEEEEEA..ACDFFCA..',
    '.........AEEAAAAAAAEEA.ACDFFCA..',
    '....GGG..AEEAAAAAAAEEEACDDFFFCA.',
    '....GGG..AEAAHGGGGGAEEAACDFFCA..',
    '....GGG..EEAHAGGGAGAEEAAACFFAA..',
    '....GGGIAEAAGGGGGGGAAEA.ACFCA...',
    '....IIIIAEAAGGGGGGGAAEA..ACA....',
    '.B...IIIIAAAGGGGGGGA.AA..AAA....',
    'BBB..IIIII.AGGGGGGGA..A...A.....',
    '.B....IIIIIAAAAAAAAA......J.....',
    '.......IIIIIAAAAAAAAA.....J.....',
    '........IIIAIKKKKKKLA.I..GG.....',
    '.........IAAIIKKKKLLAIII.GG..B..',
    '..........AAIIIIKLLLAA.IIII.BBB.',
    '..........AKIIIIKLLLAA..I.J..B..',
    '..........AIIIIMMLLLLA....J.....',
    '.........AANNNNMMNNNNA....J.....',
    '.........AANNNNMMNNNNA....J.....',
    '.........AKIIIIKKKLLLAA...J.....',
    '........AAKIIIIKKKLLLAA...J.....',
    '........AAKIIIIKKKLLLAA...J.....',
    '........AAIIIIIKKKLLLLA...J.....',
    '........AKIIIIIKKKLLLLAA..J.....',
    '.......AAKIIIIIKKKLLLLAA..J.....',
    '.......AAAAAAAAAAAAAAAAA..J.....',
    '..........AAAA....AAAA..........',
    '..........AAAA....AAAA..........',
  ]),
  Art('Wandering Bard', 'Characters', {
    'A': 0xFFE7C58C,
    'B': 0xFF243047,
    'C': 0xFF467C69,
    'D': 0xFF694739,
    'E': 0xFFFFDBB2,
    'F': 0xFFEFBA91,
    'G': 0xFFB17B4B,
    'H': 0xFFE8D2A2,
    'I': 0xFFE6BD92,
    'J': 0xFFB76370,
    'K': 0xFF604737,
    'L': 0xFF536276,
  }, [
    '................................',
    '......................AAAA......',
    '.....................AAAAA......',
    '...........B........AAA.........',
    '..........BBCBBBBBBAAA..........',
    '.........BBCCCCCCCAAAB..........',
    '........BCCCCCCCCCCACCB.........',
    '.......CCCCCCCCCCCCCCCCC........',
    '.......CCCCCCCCCCCCCCCCC........',
    '.........DDEBFFFFBFDD...........',
    '.........DDFFFFFFFFDD.....DDD...',
    '.........DDFFFFFFFFDD.....DDD...',
    '.........DDFFFFFFFFDD....GDDD...',
    '.........DDFFFFFFFFDD....GHG....',
    '..........BBBBBBBBBB....GGHG....',
    '..........BBBBBBBBBBBB.GGHG.....',
    '.........IBIIJJJJJJIIB.GHGG.....',
    '........IIIIIJJJJJJIIBIHGI......',
    '........IIBIIJJJJBBBBGIIIII.....',
    '.......IIIBIIJJBBGGGGGHGII......',
    '.......II.BIIJBGGGGGGHFFFI......',
    '.......IIIBIIBGGGGKKHGFFF.......',
    '.........IIIIFFFGKKKHGGGB.......',
    '..........BJIFFFGKKHKGGGB.......',
    '..........BJDBIGGGHKGGGGB.......',
    '..........BBDDBGGGGGGGGB........',
    '............LLLBBGGGGBB.........',
    '............LLLL.BBBBLL.........',
    '...........LLLL....LLLLL........',
    '...........LLLL....LLLLLL.......',
    '........DDDDDDD......LDDDDD.....',
    '........DDDDDDD.......DDDDD.....',
  ]),
  Art('Sakura Duelist', 'Characters', {
    'A': 0xFF243047,
    'B': 0xFF4D3E5A,
    'C': 0xFFD77794,
    'D': 0xFFF3B8BB,
    'E': 0xFFEFBA91,
    'F': 0xFFCCE4DF,
    'G': 0xFFB86887,
    'H': 0xFFE5B7BB,
    'I': 0xFFFFC857,
    'J': 0xFF694739,
    'K': 0xFF554664,
    'L': 0xFFD589A0,
    'M': 0xFF824D76,
  }, [
    '................................',
    '................................',
    '.............A..................',
    '..........AAAABAAAAA............',
    '..........ABBBBBBBBCCCC.........',
    '..........ABBAAAAABCCDDD........',
    '..........ABAAEEEEABBDDDB.......',
    '.........ABBAAEEEAABBABBB.......',
    '.........ABAAEEEEEEBBABBB....FF.',
    '.........AAAEEEEEEEABA.BB....F..',
    '...........AEEEEEEEABA.BBB..FF..',
    '...........AEEEEEEEAAA.BBB..F...',
    '...........AAAAAAAAA.A.BBB.FF...',
    '..........AAAAAAAAAAAA.BB..F....',
    '........G.AGHGGGGGGHGABGB.FF....',
    '.......GGGAGHHGGGGHHGAGGG.F.....',
    '......GGGGGGGHHGHHHHGGGGIFF.....',
    '.....GGGGGGGGHHHHHHGGGGEEII.....',
    '....GGGGGAGGGHHHHHHGGGGEFF.I....',
    '.....GGGAGGGGGHHHHHGGGAJJE......',
    '....GGGEEEKKKKIIIIKKKKAJJ.......',
    '......GEEEKKKKIIIIKKKKJJ........',
    '.......GGKKKKKKKKKKKKKJJ........',
    '.......AGGLLLLGGGMGGGGGA........',
    '.......AGGLLLLGGGMGGGGA.........',
    '.......AGGLLLLGGGGMGGGA.........',
    '........ALLLLGGGGGMGGA..........',
    '........ALLLLGGGGGMGGA..........',
    '........ALLLLGGGGGGGA...........',
    '........AAAAAAAAAAAAAA..........',
    '..........AAAA....AAAA..........',
    '..........AAAA....AAAA..........',
  ]),
  Art('Trail Scout', 'Characters', {
    'a': 0xFFC38A54,
    'b': 0xFF895439,
    'c': 0xFFFFDFB5,
    'd': 0xFFF3C49E,
    'e': 0xFF253146,
    'f': 0xFFAB5F4B,
    'g': 0xFFDA8463,
    'h': 0xFFA8D2AE,
    'i': 0xFF75AE94,
    'j': 0xFF5D463D,
    'k': 0xFF526F8E,
    'l': 0xFF344761,
  }, [
    '................',
    '......aaa.......',
    '....bbbbbb......',
    '....bbccdee.....',
    '....bbddddde....',
    '.....eddddee....',
    '..ffffgggg......',
    '...fffhhiie.....',
    '.....ehhiii.....',
    '.....eiiiidd....',
    '.....jjjekdd....',
    '.....eeeekk.....',
    '.....ellekk.....',
    '.....ellekk.....',
    '.....ejjejje....',
    '.....eeeeeee....',
  ]),
  Art('Trail Scout Walk Cycle 8 Frames', 'Characters', {
    'a': 0xFFC38A54,
    'b': 0xFF895439,
    'c': 0xFFFFDFB5,
    'd': 0xFFF3C49E,
    'e': 0xFF253146,
    'f': 0xFFAB5F4B,
    'g': 0xFFDA8463,
    'h': 0xFFA8D2AE,
    'i': 0xFF75AE94,
    'j': 0xFF526F8E,
    'k': 0xFF5D463D,
    'l': 0xFFF5D284,
    'm': 0xFF344761,
  }, [
    '......................................................aaa.............................................................aaa.......',
    '......aaa.............................aaa...........bbbbbb............aaa.............................aaa...........bbbbbb......',
    '....bbbbbb............aaa...........bbbbbb..........bbccdee.........bbbbbb............aaa...........bbbbbb..........bbccdee.....',
    '....bbccdee.........bbbbbb..........bbccdee.........bbddddde........bbccdee.........bbbbbb..........bbccdee.........bbddddde....',
    '....bbddddde........bbccdee.........bbddddde.........eddddee........bbddddde........bbccdee.........bbddddde.........eddddee....',
    '.....eddddee........bbddddde.........eddddee......ffffgggg...........eddddee........bbddddde.........eddddee......ffffgggg......',
    '..ffffgggg...........eddddee......ffffgggg.........fffhhiie.......ffffgggg...........eddddee......ffffgggg.........fffhhiie.....',
    '...fffhhiiidd.....ffffgggg.........fffhhiie..........ehhiie........fffhhiie.......ffffgggg.........fffhhiie..........ehhiedd....',
    '.....ehhieedd......fffhhiiidd........ehhiii..........eiiejie.........ehhieie.......fffhhii...........ehhiii..........eiiiidd....',
    '.....eiiiie..........ehhieedd........eiiiedd.........kkejjdd.........eiiejedd........ehhieidd........eiiiidd.........kkkejj.....',
    '.....kkkejj..........eiiiee..........kkkljdd.........eejjjdd.........kkejjjdd........eiiejedd........kkkejdd........eeeeej......',
    '....eeeeeeje.........kkkljee.........eeeejjjj.........ejjem..........ejjjeee.........kkejjje.........eeeejm.........emmejj......',
    '...emmme.ejje........eeeejjjj.........emm.ej..........ejemm.........ejjjemmme........ejjjeeme..........ejjm.........emmejj......',
    '..emmme..ejjje......mmmm...jj.........emmekke........ekkeemm......ejjjee.emmme......jjjjeemmme.........ejkke........ekkeejj.....',
    '..ekke....eekke....ekke....ekke.......ekkeeee........eeeeekke.....ekke....eekke....ekkee..eekke.......ekkeee........eeeeekke....',
    '..eeee.....eeee....eeee....eeee.......eeee...............eeee.....eeee.....eeee....eeee....eeee.......eeee..............eeee....',
  ]),
];

void main() {
  final file = File('tool/templates.json');
  final list = (json.decode(file.readAsStringSync()) as List<dynamic>).cast<Map<String, dynamic>>();

  for (final art in arts) {
    final width = art.rows.first.length;
    final pixels = <int>[];
    for (final (y, row) in art.rows.indexed) {
      if (row.length != width) {
        stderr.writeln('${art.name}: row $y has ${row.length} chars, expected $width');
        exit(1);
      }
      for (final c in row.split('')) {
        if (c == '.') {
          pixels.add(0);
        } else {
          final color = art.palette[c];
          if (color == null) {
            stderr.writeln('${art.name}: row $y uses unknown palette key "$c"');
            exit(1);
          }
          pixels.add(color);
        }
      }
    }
    final entry = {
      'name': art.name,
      'category': art.category,
      'is_pro': false,
      'width': width,
      'height': art.rows.length,
      'pixels': pixels,
    };
    final i = list.indexWhere((t) => t['name'] == art.name);
    if (i >= 0) {
      list[i] = entry;
    } else {
      list.add(entry);
    }
  }

  file.writeAsStringSync(const JsonEncoder.withIndent(' ').convert(list));
  stdout.writeln('templates.json now has ${list.length} templates');
}
